### ISSUE TITLE
Compiler issues on newly reinstalled test-osuosl-aix72-ppc64-1

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2334] opened 2021-10-04 12:30 UTC
Building jdk16 I encountered this error

```
checking if static build is enabled... disabled, default
configure: error: xlclang++ version output check failed, output: /home/jenkins/temurin-build/workspace/build/src/build/.configure-support/generated-configure.sh: line 71904: xlclang++: command not found
configure exiting with result code 1
Error: No configurations found for /home/jenkins/temurin-build/workspace/build/src.
```
This may be accounted for by an improper PATH variable while building so I'll re test this, but I also his this error while building jdk11

```
Creating hotspot/variant-server/tools/adlc/adlc from 13 file(s)
Compiling 1 files for BUILD_JFR_TOOLS
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
gmake[3]: *** [gensrc/GensrcAdlc.gmk:71: /home/jenkins/temurin-build/workspace/build/src/build/aix-ppc64-normal-server-release/hotspot/variant-server/tools/adlc/objs/output_c.o] Error 127
gmake[3]: *** Waiting for unfinished jobs....
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-222 (S) cannot fork process - Resource temporarily unavailable
```

**Comment by sxa** [comment] 2021-10-04 12:53
> `configure: error: xlclang++ version output check failed, output: /home/jenkins/temurin-build/workspace/build/src/build/.configure-support/generated-configure.sh: line 71904: xlclang++: command not found`

Does sound like a `PATH` issue although I thought that should be set correctly in [aix.sh](https://github.com/adoptium/temurin-build/blob/0829acbf6e6118b8afe50e5a554e2c144cfa7999/build-farm/platform-specific-configurations/aix.sh#L42)

> `/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable`

Hmmm I've got a feeling we've seen that one before ... May be the same as https://github.com/adoptium/infrastructure/issues/1320 although annoyingly I seemingly didn't cut & paste the error message in there.

**Comment by sxa** [comment] 2021-10-04 12:56
See also things like https://github.com/adoptium/temurin-build/issues/1450#issuecomment-578059187 which mentions `maxuproc` as being a problem in the past, but there may be other things that could help in that issue's comments.

**Comment by Haroon-Khel** [comment] 2021-10-04 15:49
While using the correct PATH variable, there still seems to be a problem with the jdk16 build

```
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/IBM/xlC/16.1.0/bin/.orig/xlclang++: error: 1501-222 cannot fork process - Resource temporarily unavailable
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/IBM/xlC/16.1.0/bin/.orig/xlclang++: error: 1501-222 cannot fork process - Resource temporarily unavailable
gmake[3]: *** [gensrc/GensrcAdlc.gmk:63: /home/jenkins/temurin-build/workspace/build/src/build/aix-ppc64-server-release/hotspot/variant-server/tools/adlc/objs/opcodes.o] Error 127
gmake[3]: *** Waiting for unfinished jobs....
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
```

Digging around, some sources seem to attribute this to a `ulimit` issue. I'll see what I can find

**Comment by aixtools** [comment] 2021-10-05 08:38
I thought the playbooks did user creation/verification:

new build:
```
root@ojdk03:[/root]ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        4194304
memory(kbytes)       unlimited
coredump(blocks)     unlimited
nofiles(descriptors) 2000
threads(per process) unlimited
processes(per user)  unlimited
root@ojdk03:[/root]su - jenkins
jenkins@ojdk03:[/home/jenkins]ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         131072
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     unlimited
nofiles(descriptors) unlimited
threads(per process) unlimited
processes(per user)  unlimited
```
older system:
```
# ulimit -a
time(seconds)        unlimited
file(blocks)         2097151
data(kbytes)         131072
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     2097151
nofiles(descriptors) 2000
threads(per process) unlimited
processes(per user)  unlimited
# su - jenkins
-bash-5.0$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) 131072
file size               (blocks, -f) unlimited
max memory size         (kbytes, -m) 32768
open files                      (-n) unlimited
pipe size            (512 bytes, -p) 64
stack size              (kbytes, -s) 32768
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
```
* Personally, not happy that both systems are SO different. THUS, look at other systems, e.g., the build-osuosl-*
* OJDK01: Almost identical (root vs jenkins)
```
root@p8-aix2-ojdk01:[/root]ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     unlimited
nofiles(descriptors) 2000
threads(per process) unlimited
processes(per user)  unlimited
root@p8-aix2-ojdk01:[/root]su - jenkins
jenkins@p8-aix2-ojdk01:[/home/jenkins]ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     unlimited
nofiles(descriptors) unlimited
threads(per process) unlimited
processes(per user)  unlimited
```
* OJDK02: Different again...
```
root@p8-aix2-ojdk02:[/root]ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        4194304
memory(kbytes)       unlimited
coredump(blocks)     unlimited
nofiles(descriptors) 2000
threads(per process) unlimited
processes(per user)  unlimited
root@p8-aix2-ojdk02:[/root]su - jenkins
jenkins@p8-aix2-ojdk02:[/home/jenkins]ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         131072
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     unlimited
nofiles(descriptors) unlimited
threads(per process) unlimited
processes(per user)  unlimited
```
* In short, looks like the playbooks are either not being used, or not effective, or manual changes are being made. Sigh.

**Comment by aixtools** [comment] 2021-10-05 08:44
Looks like it is `maxuproc` did not get fixed by the playbooks: `ojdk03` is still at **128**.
```
oot@nim.bak:[/home/root]for i in 1 2 3 4 5 6^Jdo^Jgrep ojdk0$i /etc/hosts^Jssh ojdk0$i.bak "lsattr -El sys0 -a maxuproc"^Jdone
10.1.0.7        ojdk01.bak      # ojdk1.bak
maxuproc 512 Maximum number of PROCESSES allowed per user True
10.1.0.8        ojdk02.bak      # ojdk2.bak p8-aix2-ojdk02.osuosl.bak
maxuproc 512 Maximum number of PROCESSES allowed per user True
10.1.0.12       ojdk03.bak
maxuproc 128 Maximum number of PROCESSES allowed per user True
10.1.0.16       ojdk04.bak
maxuproc 512 Maximum number of PROCESSES allowed per user True
10.1.0.4        ojdk05.bak      # p9-aix1-ojdk05.osuosl.bak
maxuproc 512 Maximum number of PROCESSES allowed per user True
10.1.0.5        ojdk06.bak ojdk06
maxuproc 512 Maximum number of PROCESSES allowed per user True
```
* Manual fix, or will the playbooks be tested again?

**Comment by Haroon-Khel** [comment] 2021-10-05 08:51
I did run the entire AIX playbook on ojdk03. Which role in the playbooks should have fixed this? If it requires a manual fix, state the fix and I'll add it to the playbooks

**Comment by aixtools** [comment] 2021-10-05 08:56
This is where is it has historically been done.

`./playbooks/scripts/AIX_filesystem_config.sh`:   `chdev -l sys0 -a maxuproc=512`

And, iirc, this is called via: `./playbooks/AdoptOpenJDK_AIX_Playbook/roles/aixfs/tasks/main.yml`

**Comment by Haroon-Khel** [comment] 2021-10-05 09:01
I see. My bad, what I meant by 'entire playbook' is I often miss that role as it was suggested to me long ago by @sej-jackson that the script's, `AIX_filesystem_config.sh`, way of expanding each filesystem is unrecommended. iirc we have an issue in this repo addressing this

**Comment by aixtools** [comment] 2021-10-05 09:05
Yes, that was the first issue I opened, and due to many misunderstandings on my part (on how ansible works) plus we have moved on, I dropped it as not resolvable by me.

Perhaps I should start over again. :)

**Comment by sxa** [comment] 2021-10-05 10:02
I've no idea why the `maxuproc` option ended up in the file system creation script but it should definitely be used elsewhere. This issue precisely demonstrates why :-)

**Comment by aixtools** [comment] 2021-10-05 10:20
That is LONG before my time. Probably because it was easier to add to a script (could it have even pre-dated the use of ansible?) than meet the requirements for ansible for command execution.

That was one of the reasons (i.e., more than just filesystem commands) I was triggered to open a issue about that file.

**Comment by sxa** [comment] 2021-11-19 12:18
@Haroon-Khel What is the status of this - do we still have compiler issues on newly installed 7.2 machines?

**Comment by aixtools** [comment] 2021-12-23 11:35
@sxa @Haroon-Khel 

The only 'issue' is that the compiler on adopt08 is more strict - as it is patched - than the compiler (GA version, no patches) - as far as xlCv16 is concerned.

Both are functioning as 'jenkins' nodes, and imho - this issue may be closed.

**Comment by aixtools** [comment] 2022-01-06 13:34
This was probably the `maxuproc` setting, that @Haroon-Khel fixed both manually and in the playbooks.

Still think it can be closed :p

**Comment by aixtools** [comment] 2022-01-09 17:13
OK. Found it.

- AIX 7.2 (7200-04-02-2028) (I'll guess AIX 7.2 TL4) includes strftime_l() (a POSIX routine), but AIX 7.2 (7200-02-05-1938) does not.
- The XLC16 include file: `/opt/IBM/xlC/16.1.0/include2/c++/support/ibm/xlocale.h` includes a code block to provide some inline code - as a static declaration. And this breaks the build.
- Not sure who to report this to - to get the message to the XLC developers. A bug - in that the include file needs to be looking at a specfic level of AIX 7.2 - when >= to skip the code block.
- So, either we re-install adopt03 again - at a lower code level - or we wait for a fix - and apply.
- For performance issues - perhaps reinstall at AIX 7.2 TL2 level.

**Comment by sxa** [comment] 2022-01-10 13:11
> The only 'issue' is that the compiler on adopt08 is more strict

Just to be clear from your last comment - is the above statement still true, or is that xlc include file that's trying to use `strftime_l()` the same for both compiler versions?

From an adopt perspective if it's only happening in the main openjdk build jobs and not when building the tests I'd be ok with not resolving this one ... Although there is an argument for querying it with the compiler team too as you say.

**Comment by aixtools** [comment] 2022-01-10 16:18
The above statement is true on adopt03, which we had upgraded the OS to AIX 7.2 TL4.
- the issue is that AIX 7.2 TL4 (or even TL3) now includes support in /usr/lib/*.a - which previously, was not there. The xlC16 include file assumes the function is not there.
- As the function exists, it is defined in the bos.adt.include fileset `/usr/include/time.h` and build's fail.
- As such, disabling the xlc16 tag is still accurate, but otherwise the node should be useable.

**Comment by aixtools** [comment] 2022-01-13 17:55
* new patch applied and fully functional.
```
Your final archive was created at /home/jenkins/temurin-build/workspace/build/src/build/aix-ppc64-server-release/images/OpenJDK.tar.gz
Moving the artifact to /home/jenkins/temurin-build/workspace/target/
build.sh : 17:12:22 : All done!
```

**Comment by aixtools** [comment] 2022-01-13 18:38
And close in the morning :)

**Comment by aixtools** [comment] 2022-01-14 11:09
success:
- jdk11: https://trss.adoptium.net/buildDetail?parentId=61e06b20a7df1a2924e63246 and https://trss.adoptium.net/buildDetail?parentId=61e06b20a7df1a2924e63248
- this ran on adopt03: https://trss.adoptium.net/allTestsInfo?buildId=61e0d3d2a7df1a2924e7f748&limit=5
- jdk17: https://trss.adoptium.net/buildDetail?parentId=61e0b7c4a7df1a2924e72a92 and https://trss.adoptium.net/buildDetail?parentId=61e0b7c4a7df1a2924e72a77
- ran on adopt03: https://trss.adoptium.net/allTestsInfo?buildId=61e12daba7df1a2924e9f59f&limit=5

- I am aware it was not used for a 'build', but it would have built!

- imho, time to close.

**Closed** 2022-01-14 13:23 UTC
Labels: os:aix, ansible, provider:osuosl

**Comment by aixtools** [comment] 2022-03-16 11:17
p.s. - only today changing the label on `adopt03` to allow xlc16 again.
