### ISSUE TITLE
System out of disk space:  build-osuosl-aix71-ppc64-2

### ISSUE THREAD

**Issue by jerboaa** [adoptium/infrastructure#2265] opened 2021-07-07 09:33 UTC
I've tried a rebuild of a successful run on this machine. The rebuild repeatedly fails with:

```
20:05:12  [WARNING] Failed to clean workspace: java.io.IOException: There is not enough space in the file system.
```

Rebuild job (July 6, 2021):
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/1046/

Successful job (July 5, 2021):
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/1042/

**Comment by sxa** [comment] 2021-07-07 09:45
Looks like one of the tests has generated some large (9Gb) core dump files which has used up everything in the filesystem.

Directory on machine: `/home/jenkins/workspace/Test_openjdk16_j9_extended.system_ppc64_aix/aqa-tests/TKG/output_16255451953314/SC_Softmx_JitAot_0/20210706-062437-SharedClassesWorkloadTest_Softmx_Increase_JitAot/results`

Test run: https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk16_j9_extended.system_ppc64_aix/96

Core files: 
```
-rw-r--r-- 1 jenkins staff 9295819170 Jul  6 06:28 core.20210706.062526.22544464.0001.dmp
-rw-r--r-- 1 jenkins staff 9295884770 Jul  6 06:30 core.20210706.062800.22544464.0008.dmp
-rw-r--r-- 1 jenkins staff 7530733568 Jul  6 06:33 core.20210706.063052.22544464.0010.dmp
```
Directory saved (After gzipping core files listed above) as /home/jenkins/infrastructureIssue2265.tar.gz - there is now 27Gb free.

Leaving this open until a suitable test issue has been raised and the need for retaining the tarball is no longer present so it can be deleted.

**Comment by aixtools** [comment] 2021-07-07 16:56
Shall I give it extra space (temporally)?

**Comment by jerboaa** [comment] 2021-07-07 16:57
It's fixed for me:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/1047/

Feel free to close.

**Comment by aixtools** [comment] 2021-07-07 17:20
:) Thx for update.

**Comment by karianna** [comment] 2021-07-07 17:57
@sxa you want this kept open as a reference or shall I just close?

**Comment by sxa** [comment] 2021-07-07 18:46
@karianna As per earlier comment I was holding off till a test issue has been raised for the unexpected core dump (Someone else can do it as I'm now on vacation) since there's presumably a real problem that caused it

**Comment by aixtools** [comment] 2021-07-08 13:05
Ther is a lot I do not know re: the build process - but it looks as if the failures for https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/ was not this job, but something else than ran before it - and did not clean up properly.

Once it was cleaned up - this particular build process completes as expected.

In short, I am doubtful there is a `test` that can be made based on the parameters used for this job.

@sxa - enjoy your vacation!

**Comment by sxa** [comment] 2021-07-14 10:06
Correct - the problem is with a test job that is generating excessively large core files and we need to attempt to replicate that and see if we still have a problem or if it is a one off.

**Comment by sxa** [comment] 2021-09-23 11:09
Going to close this as there is no sign that any recurrence is causing problems

**Closed by sxa** 2021-09-23 11:09 UTC
Labels: os:aix, provider:osuosl, systemdown
