### ISSUE TITLE
build-osuosl-aix71-ppc64-1 has named pipe issue..?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2640] opened 2022-06-24 10:06 UTC
AIX builds are failing I think with named pipe issue/leakage?
Is /tmp/sh-np.* full/too many?

https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-aix-ppc64-temurin/69/console
```
18:34:43  /opt/freeware/bin/bash: cannot make pipe for process substitution: No such file or directory
18:34:43  /opt/freeware/bin/bash: /tmp//sh-np.NB4Mab: ambiguous redirect
18:34:43  cp_64: cannot stat '/home/jenkins/workspace/build-scripts/jobs/jdk18u/jdk18u-aix-ppc64-temurin/workspace/build/src/build/aix-ppc64-server-release/support/test/hotspot/jtreg/native/support/libsetfldw003/libsetfldw003.o.log': No such file or directory
```

**Comment by sxa** [comment] 2022-06-24 10:07
File system appears to be fine - 11% space used and 15% inodes in use. Is this reproducible?

**Comment by sxa** [comment] 2022-06-24 10:09
FYI That particular file looks to have been created at 1834 UK time:
```
root@p8-aix1-adopt01:[/tmp]TZ=GMT0BST ls -ld /tmp/sh-np.NB4Mab
prw------- 1 jenkins staff 0 Jun 23 18:34 /tmp/sh-np.NB4Mab
root@p8-aix1-adopt01:[/tmp]
```

**Comment by andrew-m-leonard** [comment] 2022-06-24 10:27
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/74/console
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-aix-ppc64-temurin/69/console
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-aix-ppc64-temurin/68/console
@sxa seems reasonably repeatable

**Comment by Haroon-Khel** [comment] 2022-06-24 10:37
Not the first time we're seeing this https://github.com/adoptium/infrastructure/issues/929

**Comment by sxa** [comment] 2022-06-24 10:58
> Not the first time we're seeing this #929

My concern is that it's not clear this is the same problem since there is no indication that the file systems were full. The actions taken in there should have prevented the original problem from being seen again.

**Comment by sxa** [comment] 2022-06-24 10:58
FYI @aixtools

**Comment by aixtools** [comment] 2022-06-25 16:30
I researched this long time ago.

Most of the cases where bash is using these feature are not actually needed (when used as a mechanism to 'pipe' to tee.
However, I think I may have found a few that are needed.

I worked out a 'hack' that would resolve this for AIX, but the bash group did not feel it was the correct solution path - iow, not accepted as a PR.

Since then, just been using cron to cleanup the mess.

**Comment by sxa** [comment] 2022-07-02 06:26
I'm going to close this and continue any further discussion in [the original issue](https://github.com/adoptium/infrastructure/issues/929) in order to avoid discussion fragmentation/duplication.

I've [got a PR in](https://github.com/adoptium/temurin-build/pull/3019) which will attempt to clear it at the start of each build since the cron job does not appear to be doing an adequate job for some reason. That PR will also log to the console how many files it has found which may help diagnoses. After a JDK17u build I've just done there were 9341 left over.

**Closed by sxa** 2022-07-02 06:26 UTC
Labels: os:aix, ansible, provider:osuosl
