### ISSUE TITLE
create_windows_installer job fails on several Windows machines

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2931] opened 2023-02-13 22:15 UTC
The create_windows_installer job fails on some windows machines.  This appears to have started to fail around Feb 2nd.  

`Execution error: java.lang.Exception: [ERROR] Installer job timeout (null HOURS) has been reached OR the downstream installer job failed. Exiting...`

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure
  - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/188/console
  - https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/22118/console
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? [build-ibmcloud-win2012r2-x64-2](https://ci.adoptopenjdk.net/computer/build-ibmcloud-win2012r2-x64-2)
- Which machine(s) does it fail on? [build-ibmcloud-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/build-ibmcloud-win2012r2-x64-1) and [build-azure-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-1)

Any other details:
Console output:
```
[2023-02-12T04:50:53.579Z] Scheduling project: build-scripts » release » create_installer_windows
[2023-02-12T04:51:03.020Z] Starting building: build-scripts » release » create_installer_windows #22118
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
[2023-02-12T04:51:41.901Z] Execution error: java.lang.Exception: [ERROR] Installer job timeout (null HOURS) has been reached OR the downstream installer job failed. Exiting...
[Pipeline] echo
[2023-02-12T04:51:41.909Z] java.lang.Exception: [ERROR] Installer job timeout (null HOURS) has been reached OR the downstream installer job failed. Exiting...
[2023-02-12T04:51:41.909Z] 	at Build.build(Script1.groovy:1890)
[2023-02-12T04:51:41.909Z] 	at ___cps.transform___(Native Method)
[2023-02-12T04:51:41.909Z] 	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor1276.newInstance(Unknown Source)
[2023-02-12T04:51:41.909Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2023-02-12T04:51:41.909Z] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2023-02-12T04:51:41.910Z] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2023-02-12T04:51:41.910Z] 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
[2023-02-12T04:51:41.910Z] 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
[2023-02-12T04:51:41.910Z] 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
[2023-02-12T04:51:41.910Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
[2023-02-12T04:51:41.910Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
[2023-02-12T04:51:41.910Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$3.call(Checker.java:208)
[2023-02-12T04:51:41.910Z] 	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onNewInstance(GroovyInterceptor.java:42)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onNewInstance(SandboxInterceptor.java:173)
[2023-02-12T04:51:41.910Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$3.call(Checker.java:205)
[2023-02-12T04:51:41.910Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedConstructor(Checker.java:210)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.constructorCall(SandboxInvoker.java:21)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
[2023-02-12T04:51:41.910Z] 	at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
[2023-02-12T04:51:41.910Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-02-12T04:51:41.910Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:107)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
[2023-02-12T04:51:41.910Z] 	at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
[2023-02-12T04:51:41.910Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-02-12T04:51:41.910Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:89)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
[2023-02-12T04:51:41.910Z] 	at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
[2023-02-12T04:51:41.910Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-02-12T04:51:41.910Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
[2023-02-12T04:51:41.910Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
[2023-02-12T04:51:41.910Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
[2023-02-12T04:51:41.910Z] 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
[2023-02-12T04:51:41.910Z] 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
[2023-02-12T04:51:41.910Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-02-12T04:51:41.910Z] 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
[2023-02-12T04:51:41.910Z] 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
[2023-02-12T04:51:41.910Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
[2023-02-12T04:51:41.910Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2023-02-12T04:51:41.910Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-02-12T04:51:41.910Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2023-02-12T04:51:41.910Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2023-02-12T04:51:41.910Z] 	at java.base/java.lang.Thread.run(Thread.java:833)
[2023-02-12T04:51:41.910Z] 
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
Finished: FAILURE
```
<img width="282" alt="Screen Shot 2023-02-13 at 5 06 48 PM" src="https://user-images.githubusercontent.com/2836948/218585587-6d470e80-84df-4a8c-8876-bbac7d90a4b0.png">

**Comment by steelhead31** [comment] 2023-02-14 09:28
I believe this is now working ok, I suspect the problems on Feb 2nd, were related to the JDK upgrades that were in progress on all machines in preperation for the Jenkins upgrade, certainly, there havent been failures in the last few days, and successes on machine **build-ibmcloud-win2012r2-x64-1 (** [**here**](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/22148/console) ) and **build-azure-win2012r2-x64-1 (** [**here**](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/22145/console) **) ,** leading me to believe that these transient errors were caused by the difficulties encountered with the JDK upgrade for the jenkins agents. @smlambert I'll leave this for now, and keep an eye on it , the next couple of days, but then close it, unless it recurrs this week.

**Comment by steelhead31** [comment] 2023-02-16 09:28
Closing as no recurrence of issue.

**Closed by steelhead31** 2023-02-16 09:28 UTC
Labels: os:windows, testFail
