### ISSUE TITLE
System unavailable: Solaris machine down: https://ci.adoptopenjdk.net/label/build&&solaris&&x64/

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#1865] opened 2021-01-26 09:30 UTC
Both nodes are offline: https://ci.adoptopenjdk.net/label/build&&solaris&&x64/

**Comment by Willsparker** [comment] 2021-01-27 09:30
Ref: https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1611653435028600

`-1` is currently back online

**Comment by andrew-m-leonard** [comment] 2021-01-27 14:14
https://ci.adoptopenjdk.net/computer/build-packet_esxi-solaris10u11-x64-2/ still down

and there's something wrong with build-packet_esxi-solaris10u11-x64-1 which means it won't build:
```
13:29:57  + ./build-farm/make-adopt-build-farm.sh 
13:29:57  /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot@tmp/durable-2bce1160/script.sh: ./build-farm/make-adopt-build-farm.sh: not found
```
Even though the file is there...?!

**Comment by sxa** [comment] 2021-01-28 10:02
See https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1871 which appears to be a duplicate of the problem described in the previous comment

**Closed** 2021-06-06 16:51 UTC
Labels: arch:x64, systemdown
