### ISSUE TITLE
No space left on test-docker-alpine314-aarch64-1

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3019] opened 2023-04-06 12:26 UTC
[This test bucket](https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_x86-64_windows/32/console) failed on windows because the cupstream node (test-docker-alpine314-aarch64-1) looks to have run out of space while uploading the tap/results files afterwards.

```
java.nio.file.FileSystemException: /home/jenkins/workspace/Test_openjdk20_hs_extended.openjdk_x86-64_windows: No space left on device
```

Please take a look.

P.S. I'm happy to handle these sorts of issues myself if I could get ssh access to all of the test machines. Is that a simple todo?

**Comment by smlambert** [comment] 2023-04-06 15:10
I do not believe having access to these test-docker* nodes (which are static docker containers) helps fix the 'No space left on device' issue.  [test-docker-alpine313-aarch64-1](https://ci.adoptium.net/computer/test-docker-alpine313-aarch64-1/) and  [test-docker-alpine314-aarch64-1](https://ci.adoptium.net/computer/test-docker-alpine314-aarch64-1/)are hosted on [hw.dockerhost.alpine-linux.dockerhost-equinix-ubuntu2004-armv8-1](https://ci.adoptium.net/label/hw.dockerhost.alpine-linux.dockerhost-equinix-ubuntu2004-armv8-1).

Some actions that should happen are:
- running a `docker prune` on the dockerhost node that the static test-docker* containers that hosted on
- since this is now a very regular recurring issue
  - understand why the dockerhost is filling up so often and potentially addressing the core issue (Related: https://github.com/adoptium/infrastructure/issues/3007)
  - schedule a script that would run `docker prune` on the dockerhost machines regularly (doesn't help determine or fix core issue, but prevents side effects of running out of space)

**Comment by sxa** [comment] 2023-04-06 16:58
This is a log from four days ago and is effectively a duplicate of https://github.com/adoptium/infrastructure/issues/3017.

The problem is not present just now.

**Closed by sxa** 2023-04-06 16:58 UTC
Labels: docker, testFail
