### ISSUE TITLE
build-osuosl-aix71-ppc64-* failing jdk_lang jdk_util tests

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2069] opened 2021-03-22 14:48 UTC
Both grinders on the build-osuosl machines still failed the following tests despite the symlinks being in place
```
jdk_lang_1
jdk_util_1
```
with the same error
```
LD_LIBRARY_PATH= : 	0509-022 Cannot load module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/libawt_xawt.so.
13:52:59  	0509-150   Dependent module /opt/freeware/lib/libXrender.a(shr_64.o) could not be loaded.
13:52:59  	0509-152   Member shr_64.o is not found in archive
```

_Originally posted by @Haroon-Khel in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1697#issuecomment-804111475_

**Comment by Haroon-Khel** [comment] 2021-03-22 14:56
Related link 
https://www.ibm.com/support/pages/ibm-java-aix-how-resolve-unsatisfiedlinkerror-gui-based-application

**Comment by sxa** [comment] 2021-03-22 15:27
@Haroon-Khel See https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1772#issuecomment-750373467 for potential things to try to reproduce the problem. That issue contains a small standlone java test case that might allow you to replicate it outside all the test harnesses.

**Comment by aixtools** [comment] 2021-03-23 08:16
Perhaps we need `ojdk06` in the grinder system - so that test results get captured for all - but only as a wildcard - so that different setups can be tested.

* When these tests fail - are they failing from something they just built? Or are they failing against a java image they just installed - meaning, was built on a different AIX system?
* If the failing java was not `just built` then the issue may have it's origin in the system config of the building system, not the config of the running system.

**Comment by aixtools** [comment] 2021-03-23 08:27
@Haroon-Khel your link above is for the unfortunate `user` that has to work with a JVM asis - and how to repair the AIX environment so that it can work.

IMHO: we are in a different situation: we are building the JVM and need to make sure that these issues do not occur rather than create a dependency on an AIX Toolbox (unsupported) package.

In the other issue: #1772 I guessed that this is being caused by a ./configure issue and a missing include file - and that libXrender-devel (plus it's requirements) gets installed to satisify a missing include file.

Looking further - it may be that this time - IBM does include the include file, but configure is not finding it:

```
p159a01:/ # find /usr /opt -name Xrender.h
/usr/lpp/X11/include/X11/extensions/Xrender.h
/opt/freeware/include/X11/extensions/Xrender.h

p159a01:/ # rpm -ql libXrender-devel | grep Xrender.h
/opt/freeware/include/X11/extensions/Xrender.h

p159a01:/ # lslpp -w /usr/lpp/X11/include/X11/extensions/Xrender.h
  File                                        Fileset               Type
  ----------------------------------------------------------------------------
  /usr/lpp/X11/include/X11/extensions/Xrender.h
                                                 X11.adt.ext        File
```

So, rather than focus on trying to fix libraries - let's take a step back and see why libXrender.RPM (or likely more accurately, libXrender-devel.RPM) is needed/what motivated the install in the first place!

**Comment by sxa** [comment] 2021-03-23 09:35
> @Haroon-Khel your link above is for the unfortunate `user` that has to work with a JVM asis - and how to repair the AIX environment so that it can work.
> 
> IMHO: we are in a different situation: we are building the JVM and need to make sure that these issues do not occur rather than create a dependency on an AIX Toolbox (unsupported) package.
> 
> In the other issue: #1772 I guessed that this is being caused by a ./configure issue and a missing include file - and that libXrender-devel (plus it's requirements) gets installed to satisify a missing include file.
> 
> Looking further - it may be that this time - IBM does include the include file, but configure is not finding it:
> 
> ```
> p159a01:/ # find /usr /opt -name Xrender.h
> /usr/lpp/X11/include/X11/extensions/Xrender.h
> /opt/freeware/include/X11/extensions/Xrender.h
> 
> p159a01:/ # rpm -ql libXrender-devel | grep Xrender.h
> /opt/freeware/include/X11/extensions/Xrender.h
> 
> p159a01:/ # lslpp -w /usr/lpp/X11/include/X11/extensions/Xrender.h
>   File                                        Fileset               Type
>   ----------------------------------------------------------------------------
>   /usr/lpp/X11/include/X11/extensions/Xrender.h
>                                                  X11.adt.ext        File
> ```
> 
> So, rather than focus on trying to fix libraries - let's take a step back and see why libXrender.RPM (or likely more accurately, libXrender-devel.RPM) is needed/what motivated the install in the first place!

OpenJDK builds require it - it's mentioned in the builfd logs:
```
18:14:53  checking for X11/extensions/Xrender.h... yes
```

**Comment by aixtools** [comment] 2021-03-23 10:30
* Yes, and I think an ansible entry or entries to create a symbolic link from /usr/include/X11/extensions/Xrender.h to /usr/lpp/X11/include/X11/extensions/Xrender.h is better
* than (?) adding /opt/freeware/include to CFLAGS (just a guess for now).

**Comment by sxa** [comment] 2021-03-24 20:05
@aixtools I think I'm missing something - the original issue described was about an inability to link to the library - how have you gone back to trying to fix an issue with the header files? Is that related to the initially described problem?

**Comment by aixtools** [comment] 2021-03-25 08:12
Yes - as to why the additional libraries were installed.

Quick test is to remove the RPM packages I mentioned.
* If a subsequent retry fails due to missing Xrender.h - then create the symlink I suspect will fix that, and try again.
* In other words, the problem is that the RPM library should not be there to begin with. If it isn't there it cannot cause a side effect that it is missing the contents (other AIX) libraries are expecting.

**Comment by Haroon-Khel** [comment] 2021-03-26 17:34
On build-osuosl-aix71-ppc64-1
```
bash-5.0# dump -Xany -H /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/libawt_xawt.so

/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/libawt_xawt.so:

                        ***Loader Section***
                      Loader Header Information
VERSION#         #SYMtableENT     #RELOCent        LENidSTR
0x00000001       0x000004dc       0x00000a80       0x000001b5       

#IMPfilID        OFFidSTR         LENstrTBL        OFFstrTBL
0x0000000c       0x00011cd8       0x00008865       0x00011e8d       


                        ***Import File Strings***
INDEX  PATH                          BASE                MEMBER              
0      /opt/IBM/xlc/13.1.3/../../../../usr/lpp/xlC/lib:/opt/IBM/xlC/13.1.3/lib/aix61:/opt/IBM/xlC/13.1.3/lib:/opt/IBM/xlc/13.1.3/lib/aix61:/opt/IBM/xlc/13.1.3/lib:/usr/vac/lib/aix53:/opt/freeware/lib/pthread/ppc64:/opt/freeware/lib:/usr/lib                                         
1                                    libawt.so                               
2                                    libXext.a           shr_64.o            
3                                    libX11.a            shr_64.o            
4                                    libXrender.a        shr_64.o            
5                                    libdl.a             shr_64.o            
6                                    libXtst.a           shr_64.o            
7                                    libXi.a             shr_64.o            
8                                    libjava.so                              
9                                    libjvm.so                               
10                                   libpthreads.a       shr_xpg5_64.o       
11                                   libc.a              shr_64.o 
```

In it's PATH, /opt/freeware/lib is in front of /usr/lib and its the /opt/freeware/lib/libXrender.a that its looking for, not /usr/lib/libXrender.a 

Ive checked all the other directories in that PATH, and they do not have their own libXrender.a files

**Comment by Haroon-Khel** [comment] 2021-03-26 17:48
Reinstalled libXrender and its dependencies on build-osuosl-1. Running jdk_util tests on it
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8040/console

**Comment by sxa** [comment] 2021-03-26 18:03
That search path will be controlled by the same line that was last changed in https://github.com/AdoptOpenJDK/openjdk-build/pull/2489 on Feb 23rd but that change won't have affected this problem. It does explain where those entries have come from though -  it's from the `LIBPATH` that is set during the build.

Based on:
> Yes - as to why the additional libraries were installed.

So they come from the `libXrender` RPM package, which I assume is pulled in as a dependency of `libXrender-devel` (We could try doing `rpm -e libXrender` and see if it blocks on `libXrender-devel`.

However as @aixtools says:
> Yes, and I think an ansible entry or entries to create a symbolic link from /usr/include/X11/extensions/Xrender.h to /usr/lpp/X11/include/X11/extensions/Xrender.h is better

That would work, although I'd  rather avoid extra symlinks if we can avoid it so if that if the AIX-provided `Xrender.h` from `X11.adt.ext` is good enough to build with then we may be able to try building with  e.g. `--with-extra-cflags=-I/usr/lpp/X11/include --with-extra-cxxflags=-I/usr/lpp/X11/include` (Possibly doesn't need the `cxx` one though) - see https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/aix.sh#L40 for an example of where such flags it can be set.

**Comment by aixtools** [comment] 2021-04-02 12:33
I just looked at the existing `platform-specific-configurations` for AIX and it might be even easier than expected:

* currently there is:
```export LIBPATH=/opt/freeware/lib/pthread/ppc64:/opt/freeware/lib:/usr/lib```
* rather than prepend - append - so:
```export LIBPATH=/usr/lib:/opt/freeware/lib/pthread/ppc64:/opt/freeware/lib```
* as one of the libraries in /opt/freeware/bin is LibXrender

* IMHO: The AIX library should always be used UNLESS it is shown to be broken - and IBM refuses to repair it. Just because /opt/freeware/lib is used by both BULL and IBM AIXToolbox - does not mean a customer can ever open a ticket on anything there. And should OpenJDK fail because of a library issue in /opt/freeware/lib - they will, correctly, just refer it back to OpenJDK and the choice to use a non-supported library (meaning 'we' OpenJDK must give the support AIXToolbox et al is not expected to give).

**Comment by aixtools** [comment] 2021-04-02 12:43
* I want to add
a) it is one thing to add a library not provided by IBM Systems (aka AIX bos)
b) it is another matter to replace a library provided by IBM - because any issues caused by the replacement library are *never* going to be recognized by IBM

* Moving to the customer perspective - there is an issue with /usr/lib/libXYZ.a - and a work around is to install an OSS produced version of libXYZ.a (e.g., a symbolic link in /usr/lib to /opt/OSS/lib/libXYZ.a
* Now the customer can open a ticket - complaining about a defect in IBM provided /usr/lib/libXYZ.a because program DBCA works fine with the OSS library where the defect is fixed. IBM support - patch your version so that it works with DBCA, etc..

**Comment by aixtools** [comment] 2021-04-07 11:29
Are we going to test this?

**Comment by Haroon-Khel** [comment] 2021-04-08 14:16
Recent jdk11 openjdk sanity test passes on build-osuosl-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8161/console

Running one of -2 aswell
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8163/console

**Comment by Haroon-Khel** [comment] 2021-04-08 14:17
@aixtools It may be abit of a reach, but would this have anything to do with https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1651#issuecomment-814661393 ?

**Comment by Haroon-Khel** [comment] 2021-04-08 18:42
The tests on -2 passed aswell

**Comment by aixtools** [comment] 2021-04-13 08:36
> 
> 
> @aixtools It may be abit of a reach, but would this have anything to do with [#1651 (comment)](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1651#issuecomment-814661393) ?

No. not related.

**Comment by aixtools** [comment] 2021-04-13 08:56
> 
> 
> @aixtools I think I'm missing something - the original issue described was about an inability to link to the library - how have you gone back to trying to fix an issue with the header files? Is that related to the initially described problem?

I am not clear on whether this is a fresh build that is testing itself, or a test job that downloads a 'pre-built' from a different location and then tests that. My expectation is that a `fresh build` would work, but a build coming from somewhere else may fail due to differences in library installation.

* What I want to repeat is that the library libXrender.a exists on AIX - and is the system default. Further - it seems on `ojdk03` and `ojdk04` the RPM package with the library is not installed.
```root@nim.bak:[/home/root]for i in 1 2 3 4 5 6^Jdo ^Jprint ojdk0$i^Jssh ojdk0$i.bak "find /usr /opt -name libXrender.a -ls" ^Jdone
ojdk01
13814    1 lrwxrwxrwx  1 bin       bin             32 Jul  2  2020 /usr/lib/libXrender.a -> /usr/lpp/X11/lib/R7/libXrender.a
274449  165 -rw-r--r--  1 bin       bin         168948 Jul 14  2014 /usr/lpp/X11/lib/R7/libXrender.a
82091  928 -rwxr-xr-x  1 root      system      949342 May 29  2018 /opt/freeware/lib/libXrender.a
ojdk02
13813    1 lrwxrwxrwx  1 bin       bin             32 Jul  2  2020 /usr/lib/libXrender.a -> /usr/lpp/X11/lib/R7/libXrender.a
278545  165 -rw-r--r--  1 bin       bin         168948 Jul 14  2014 /usr/lpp/X11/lib/R7/libXrender.a
67416  928 -rwxr-xr-x  1 root      system      949342 May 29  2018 /opt/freeware/lib/libXrender.a
ojdk03
 2037    1 lrwxrwxrwx  1 bin       bin             32 Jul  5  2018 /usr/lib/libXrender.a -> /usr/lpp/X11/lib/R7/libXrender.a
47348  161 -rw-r--r--  1 bin       bin         164852 Jun  1  2015 /usr/lpp/X11/lib/R7/libXrender.a
ojdk04
 2037    1 lrwxrwxrwx  1 bin       bin             32 Jul  5  2018 /usr/lib/libXrender.a -> /usr/lpp/X11/lib/R7/libXrender.a
47348  161 -rw-r--r--  1 bin       bin         164852 Jun  1  2015 /usr/lpp/X11/lib/R7/libXrender.a
ojdk05
 1815    1 lrwxrwxrwx  1 bin       bin             32 Sep 14  2020 /usr/lib/libXrender.a -> /usr/lpp/X11/lib/R7/libXrender.a
111846  165 -rw-r--r--  1 bin       bin         168948 Apr 23  2018 /usr/lpp/X11/lib/R7/libXrender.a
 8293  928 -rwxr-xr-x  1 root      system      949342 May 29  2018 /opt/freeware/lib/libXrender.a
ojdk06
13105    1 lrwxrwxrwx  1 bin       bin             32 Mar 22 12:46 /usr/lib/libXrender.a -> /usr/lpp/X11/lib/R7/libXrender.a
108344  161 -rw-r--r--  1 bin       bin         164852 Jun  1  2015 /usr/lpp/X11/lib/R7/libXrender.a
  132  928 -rwxr-xr-x  1 root      system      949342 May 29  2018 /opt/freeware/lib/libXrender.a
```

As to the include file:
AIX **ALSO** includes the file by default - and surprisingly - the RPM with the include file is installed on **ALL**
```
ojdk01
270584   14 -rw-r--r--  1 bin       bin          14160 Sep 21  2009 /usr/lpp/X11/include/X11/extensions/Xrender.h
79078   13 -rw-r--r--  1 root      system       12805 May 29  2018 /opt/freeware/include/X11/extensions/Xrender.h
ojdk02
275881   14 -rw-r--r--  1 bin       bin          14160 Sep 21  2009 /usr/lpp/X11/include/X11/extensions/Xrender.h
66565   13 -rw-r--r--  1 root      system       12805 May 29  2018 /opt/freeware/include/X11/extensions/Xrender.h
ojdk03
90794   14 -rw-r--r--  1 bin       bin          14160 Sep 21  2009 /usr/lpp/X11/include/X11/extensions/Xrender.h
48784   13 -rw-r--r--  1 root      system       12805 May 29  2018 /opt/freeware/include/X11/extensions/Xrender.h
ojdk04
93961   14 -rw-r--r--  1 bin       bin          14160 Sep 21  2009 /usr/lpp/X11/include/X11/extensions/Xrender.h
41288   13 -rw-r--r--  1 root      system       12805 May 29  2018 /opt/freeware/include/X11/extensions/Xrender.h
ojdk05
348885   14 -rw-r--r--  1 bin       bin          14160 Sep 21  2009 /usr/lpp/X11/include/X11/extensions/Xrender.h
73755   13 -rw-r--r--  1 root      system       12805 May 29  2018 /opt/freeware/include/X11/extensions/Xrender.h
ojdk06
119373   14 -rw-r--r--  1 bin       bin          14160 Sep 21  2009 /usr/lpp/X11/include/X11/extensions/Xrender.h
106586   13 -rw-r--r--  1 root      system       12805 May 29  2018 /opt/freeware/include/X11/extensions/Xrender.h
```
* IMHO: the RPM should be removed - and quickfix is a sym-link from /usr/include to /usr/lpp/X11/include/X11/extensions/Xrender.h - and a longer term solution is the change to an argument - as @sxa mentioned.

**Comment by aixtools** [comment] 2021-04-14 12:47
Update: Looking at TRSS: For AIX:
![image](https://user-images.githubusercontent.com/10852597/114711870-bf185a00-9d2f-11eb-9ef2-17dc3eff7323.png)

The 'unstable' for AIX is:
![image](https://user-images.githubusercontent.com/10852597/114712140-0b639a00-9d30-11eb-8a27-5ac261b56c0f.png)

These 4 tests all fail due to:
```
Standard Error

java.lang.RuntimeException: Unexpected exception: java.lang.UnsatisfiedLinkError: /home/jenkins/workspace/Test_openjdk16_hs_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/libawt_xawt.so: /home/jenkins/workspace/Test_openjdk16_hs_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/libawt_xawt.so, LIBPATH=/home/jenkins/workspace/Test_openjdk16_hs_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Test_openjdk16_hs_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdk16_hs_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/../lib, LD_LIBRARY_PATH= : Could not load module /home/jenkins/workspace/Test_openjdk16_hs_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/libawt_xawt.so.
	Dependent module /opt/freeware/lib/libXrender.a(shr_64.o) could not be loaded.
	Member shr_64.o is not found in archive 
	
```
* Goiing to rename the GNU 'libXrender.a' on build-osuosl-aix71-ppc64-2 (as it is not in the `ci.role.test` group - and see if it passes:

**Comment by Haroon-Khel** [comment] 2021-04-16 13:51
Rerunning jdk 11 hotspot openjdk sanity tests on [-1](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/121/console) and [-2](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/122/console)

**Comment by sxa** [comment] 2021-04-16 16:45
The run on `-1` has passed although the one on `-2` seems to be taking a lot of time ... But still progressing.

**Comment by aixtools** [comment] 2021-04-19 09:55
* I just ran https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/124/ - with the OSS libXrender.a 'disabled', and https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/125/ with the library enabled.
* test # 124 passed
* test # 125 - fails as expected
* further details (of 125)
```
JavaTest Message: Test threw exception: java.lang.RuntimeException: Unexpected exception: java.lang.UnsatisfiedLinkError: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/libawt_xawt.so: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/libawt_xawt.so, LIBPATH=/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/server:/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64:/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/jli:/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/../lib/ppc64, LD_LIBRARY_PATH= :     0509-022 Cannot load module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/libawt_xawt.so.
        0509-150   Dependent module /opt/freeware/lib/libXrender.a(shr_64.o) could not be loaded.
        0509-152   Member shr_64.o is not found in archive
        0509-022 Cannot load module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/libawt_xawt.so.
        0509-150   Dependent module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/libawt_xawt.so could not be loaded.
JavaTest Message: shutting down test


root@ojdk01:[/opt/freeware/lib]ls -ld *X*
-rwxr-xr-x 1 root system 1565634 May 29  2018 libXft.a
-rwxr-xr-x 1 root system  568202 May 29  2018 libXft.so.2
-rwxr-xr-x 2 root system  949342 May 29  2018 libXrender.a
-rwxr-xr-x 2 root system  949342 May 29  2018 libXrender.a.issue2069
-rwxr-xr-x 1 root system     911 May 29  2018 libXrender.la
root@ojdk01:[/opt/freeware/lib]ar tv libXrender.a
rwxr-xr-x     0/0     383091 May 29 11:13 2018 libXrender.so.1
rw-r--r--     0/0      72911 May 29 11:13 2018 libXrender.so.0
root@ojdk01:[/opt/freeware/lib]ar tv /usr/lib/libXrender.a
rwxr-x---   300/300    70806 Jul 14 16:36 2014 shr.o
rw-r-----   300/300     5495 Oct 27 04:58 2007 libXrender.so.0
```
* Over the weekend this test failed on https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/348/ - will 'disable' the OSS library and rerun from test # 348 - setting label to `test-ibm-aix71-ppc64-2`

**Comment by aixtools** [comment] 2021-04-19 14:41
As https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/126/console - passes on `test-ibm-aix71-ppc64-2` I propose:
* to remove the OSS package Xrender - asap.
* modify playbooks to not install Xrender

@sxa comments please.

**Comment by sxa** [comment] 2021-04-19 16:57
Is be somewhat resultant to make any changes one day before a release cycle

**Comment by aixtools** [comment] 2021-04-20 13:45
* Well, been testing for weeks - and I knew the answer weeks ago.
* I can put everything back in the breaking mode, or update all in the passing mode.

* Change via PR comes later, obviously.

**Comment by sxa** [comment] 2021-04-20 14:12
> Change via PR comes later, obviously.

Put the PR in now if you can please - we just won't integrate it until next week, but it gives a few days for reviews :-)

**Comment by aixtools** [comment] 2021-04-21 07:30
As these are RPM's - a bit of research shows the likely list of RPM's to no longer be installing is more than 'just' Xrender - due to the so-called dependencies:

```
root@p9-aix1-ojdk06:[/root]rpm -qa | grep Xrender
libXrender-devel-0.9.8-2waixX11.ppc
libXrender-0.9.8-2waixX11.ppc
root@p9-aix1-ojdk06:[/root]rpm --test -e libXrender
error: Failed dependencies:
        libXrender = 0.9.8-2waixX11 is needed by (installed) libXrender-devel-0.9.8-2waixX11.ppc
        libXrender >= 0.9.5 is needed by (installed) libXft-2.3.2-4waixX11.ppc
        libXrender.a(libXrender.so.1) is needed by (installed) libXft-2.3.2-4waixX11.ppc
root@p9-aix1-ojdk06:[/root]rpm --test -e libXft
error: Failed dependencies:
        libXft.a(libXft.so.2) is needed by (installed) tk-8.6.8-3.ppc
root@p9-aix1-ojdk06:[/root]rpm --test -e tk
root@p9-aix1-ojdk06:[/root]
root@p9-aix1-ojdk06:[/root]rpm --test -e tcl
error: Failed dependencies:
        libtcl8.6.so is needed by (installed) expect-5.45.4-1.ppc
        libtcl8.6.so is needed by (installed) tk-8.6.8-3.ppc
        tcl >= 8.6.8-3 is needed by (installed) expect-5.45.4-1.ppc
        tcl = 8.6.8-3 is needed by (installed) tk-8.6.8-3.ppc
root@p9-aix1-ojdk06:[/root]rpm --test -e expect
```
* expect
* tcl
* tk
* libXft
* libXrender-devel
* libXrender

* I hope that is resolvable via `yum:` and `state: absent`

* Fortunately - none of these are needed by `python` - they say. I am not completely sure about the accuracy however.
* * I know git does not need python to run (only to build)
* * python might need tk/tcl/expect to run the related (python optional) modules

**Comment by andrew-m-leonard** [comment] 2021-06-30 11:05
@Haroon-Khel this failed again on  test-osuosl-aix71-ppc64-2
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/381/console

**Comment by Haroon-Khel** [comment] 2021-07-02 11:36
This test fails on all of our aix machines
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1006/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1006/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1006/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1006/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1006/console

**Comment by sxa** [comment] 2021-07-05 11:41
FYI @sej-jackson

**Comment by aixtools** [comment] 2021-07-26 12:26
Let's go back to the beginning:
```
LD_LIBRARY_PATH= : 	0509-022 Cannot load module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/libawt_xawt.so.
13:52:59  	0509-150   Dependent module /opt/freeware/lib/libXrender.a(shr_64.o) could not be loaded.
13:52:59  	0509-152   Member shr_64.o is not found in archive
```
The loader does not find shr_64.o - because this is was found in /usr/lib/libXrender.a during compile:
```
root@p9-aix1-ojdk06.osuosl.org:[/root]ar -X64 tv /usr/lib/libXrender.a
rwxr-x---   300/300    76635 Apr 23 15:23 2018 shr_64.o
rw-r-----   300/300     5737 Oct 27 04:58 2007 libXrender.so.0
```
p.s. - I see yet another surprise - considering the file modes of the archive members. Surprised they were found during the build!
* No regular user has either UID or GID == 300.
@sej-jackson - if you could file a PMR with IBM to mention that these shared libraries are not `readable` by `other` - would be excellent!

* Back to issue: despite my surprise - shr_64.o is being located during the build process, but does not exist in the RPM based packaging:
```
root@p9-aix1-ojdk05:[/root]ar -X64 tv /opt/freeware/lib/libXrender.a-SXAMOVED1172
rwxr-xr-x     0/0     407535 May 29 11:13 2018 libXrender.so.1
rw-r--r--     0/0      77577 May 29 11:13 2018 libXrender.so.0
```

With permission - I would like to remove the RPM packages on ojdk05 (aka test-osuosl-aix72-1):
* expect
* libXft
* libXrender-devel
* LibXrender

Maybe another dependency shows up - I'll add that to this issue, and make the PR changes once the system configuration 'passes' what people need to build stuff.

Note: might find some C code that needs a change to the name given for Xrender.h, e.g., change `#include <Xrender.h>` to `#include <X11/extensions/Xrender.h>`

**Comment by smlambert** [comment] 2021-08-17 13:35
I'd like to take these machines offline if this is not yet resolved, since when we land on them, it results in ~100 test failures and creates unwanted noise / triage.

**Comment by sxa** [comment] 2021-08-18 12:17
@Haroon-Khel In light of Shelley's comments can we try and get this to a conclusion please? My suggestion would be to use ojdk06 for any testing that is required to verify the proposals which Michael has suggested.

**Comment by aixtools** [comment] 2021-08-18 20:32
ojdk06 is an aix72 system. Shall I reinstall with aix71 and my suggestions?

**Comment by aixtools** [comment] 2021-08-20 10:41
reinstall? Or work on 'asis'?

**Comment by aixtools** [comment] 2021-08-20 11:20
Back to March:

    So, rather than focus on trying to fix libraries - let's take a step back and see why libXrender.RPM (or likely more accurately, libXrender-devel.RPM) is needed/what motivated the install in the first place!

OpenJDK builds require it - it's mentioned in the builfd logs:

18:14:53  checking for X11/extensions/Xrender.h... yes

The check is not finding the IBM provided Xrender.h, so RPM Xrender gets installed, but the build seems to be linking against the IBM Xrender library.

As @sxa commented, iirc, earlier - this should likely be fixed in the configure script (i,e., check for <X11/extensions/Xrender.h>

rather than #include <Xrender.h>, installing the RPM, and adding CFLAGS=-I/opt/include/X11/entensions.

@smlambert -- while it can be fixed via infrastrure, has anyone actually looked at a PR for ./configure?

a) seeing the test is failing on all systems, I'll just make some changes on ojdk06.
b) if someone will assist - I'll 'also assist' with testing a change in the `configure` tests.

**Comment by aixtools** [comment] 2021-08-20 11:55
To test ---
```
rpm -e libXrender libXft libXrender-devel tk renderproto

# to get the system to point at the IBM installed X11 extenstions
rmdir /opt/freeware/include/X11/extensions
ln -s /usr/include/X11/extensions /opt/freeware/include/X11/extensions
```
* Running Grinder: https://ci.adoptopenjdk.net/job/Grinder/1228/
* just noticed this system had been reinstalled with AIX 7.1 some time back. So, the reinstall had already been done.

**Comment by aixtools** [comment] 2021-08-20 12:27
I must not be understanding 'something', i.e., have probably fogoteen how to specify a proper grinder job:

```
00:14:29.382  Running jdk_util ...
00:14:29.382  There is no test for target jdk_util
```

**Comment by smlambert** [comment] 2021-08-20 12:55
Updated your grinder to use BUILD_LIST=openjdk (versus the default value of BUILD_LIST=functional), so that the openjdk test targets get parsed (and test material gets compiled).

Rerun here: https://ci.adoptopenjdk.net/job/Grinder/1229/

**Comment by aixtools** [comment] 2021-08-20 14:15
Thanks @smlambert - just finished with a PASS.

Are we okay to do this moving forward (@sxa) - AND, considering your comment above - are you (@smlambert ) okay with the results based on this test, or do you want to run additional tests?

**Comment by aixtools** [comment] 2021-08-22 14:47
Testing again - just removing the link to the include files - to be sure that bit is being tested.
```
root@p9-aix1-ojdk06.osuosl.org:[/opt/freeware/include/X11]mv extensions extensions.IBM
root@p9-aix1-ojdk06.osuosl.org:[/opt/freeware/include/X11]
```
https://ci.adoptopenjdk.net/job/Grinder/1237/

**Comment by aixtools** [comment] 2021-08-22 14:56
Further, I see the system is not equivalent with the build-*{1|2} as they are oslevel
```
root@p8-aix2-ojdk01:[/root]oslevel -s -q | head
Known Service Packs
-------------------
7100-04-04-1717
```
While the test system is:
```
root@p9-aix1-ojdk06.osuosl.org:[/opt/freeware/include/X11]oslevel -s -q | head
Known Service Packs
-------------------
7100-05-06-2028
```

So we are NOT testing equivalent kernel settings.

**Comment by aixtools** [comment] 2021-09-25 11:52
This is also related to #1772 . Will add comment asap - here and #infrastructure

**Comment by aixtools** [comment] 2021-09-25 12:06
https://github.com/adoptium/infrastructure/issues/2069#issuecomment-902639183

```
root@p8-aix2-ojdk02:[/root]rpm -e libXrender libXft libXrender-devel tk renderproto
warning: file /opt/freeware/lib/libXrender.a: remove failed: A file or directory in the path name does not exist.
```
* the file had already been renamed - making it appear asif the RPM was already de-installed.
* Now removing these files as well - to complete the cleanup:
```
root@p8-aix2-ojdk02:[/root]ls -l /opt/freeware/lib/libX*
-rwxr-xr-x 1 root system 722338 Mar 28  2017 /opt/freeware/lib/libXrender.a-SXAMOVED
-rwxr-xr-x 1 root system 949342 May 29  2018 /opt/freeware/lib/libXrender.a.issue2069

root@p8-aix2-ojdk02:[/root]rm /opt/freeware/lib/libX*

# to get the system to point at the IBM installed X11 extenstions
rmdir /opt/freeware/include/X11/extensions
ln -s /usr/include/X11/extensions /opt/freeware/include/X11/extensions
```
* If the build now succeeds, the symbolic link should be removed, (https://github.com/adoptium/infrastructure/issues/2069#issuecomment-903280080)
and the test repeated. When it fails, the AIX include directive should be:
`#include <X11/extensions/Xrender.h>`

ie, needs a change in configure.ac for AIX to look in X11/extensions - rather than add `/usr/include/X11/extensions` to cflags -
I expect it is `/opt/freeware/include/X11/extensions` atm.

**Comment by sxa** [comment] 2021-09-27 12:03
Build at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/1001/consoleFull succeeded on [build-osuosl-aix71-ppc64-2](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-2) after the changes described above.

**Comment by aixtools** [comment] 2021-09-29 11:27
I cannot run this job, so needs verification after doing:
```
root@p8-aix2-ojdk02:[/root]ls -ld /usr/include/X11/extensions /opt/freeware/include/X11/extensions
lrwxrwxrwx 1 root system   27 Sep 25 12:00 /opt/freeware/include/X11/extensions -> /usr/include/X11/extensions
drwxr-xr-x 2 bin  bin    4096 Feb 18  2021 /usr/include/X11/extensions
root@p8-aix2-ojdk02:[/root]rm /opt/freeware/include/X11/extensions
```
The PR #2330 also removes this directory.

**Comment by aixtools** [comment] 2021-09-30 07:31
Since I cannot run a build via the web-interface and jenkins, I tried using:

```
git clone  https://github.com/adoptium/temurin-build.git
cd temurin-build
./makejdk-any-platform.sh jdk11u
```
This completed successfully.

**Closed** 2021-10-01 09:25 UTC
Labels: os:aix, provider:osuosl
