### ISSUE TITLE
jdk11 java/beans/Beans/TypoInBeanDescription.java timeout on test-osuosl-aix715-ppc64-3

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2643] opened 2022-06-27 19:09 UTC
java/beans/Beans/TypoInBeanDescription.java timeout on [test-osuosl-aix715-ppc64-3](https://ci.adoptopenjdk.net/computer/test-osuosl-aix715-ppc64-3)

on passed machine https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5044

- test suite/name?
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? [build-osuosl-aix71-ppc64-2](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-2)
- Which machine(s) does it fail on? [test-osuosl-aix715-ppc64-3](https://ci.adoptopenjdk.net/computer/test-osuosl-aix715-ppc64-3)
- Do you have a link to a Grinder re-run if the test with the failure?
 rerun
on failed machine https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5042/
on passed machine https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5044

**Comment by Haroon-Khel** [comment] 2022-07-06 16:43
Rerunning

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5104/console
[test-osuosl-aix715-ppc64-3](https://ci.adoptopenjdk.net/computer/test-osuosl-aix715-ppc64-3/)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5105/console
[test-osuosl-aix72-ppc64-2](https://ci.adoptopenjdk.net/computer/test-osuosl-aix72-ppc64-2/)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5106/console
[test-osuosl-aix72-ppc64-1](https://ci.adoptopenjdk.net/computer/test-osuosl-aix72-ppc64-1/)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5107/console
[test-osuosl-aix715-ppc64-1](https://ci.adoptopenjdk.net/computer/test-osuosl-aix715-ppc64-1/)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5108/console
[test-osuosl-aix715-ppc64-2](https://ci.adoptopenjdk.net/computer/test-osuosl-aix715-ppc64-2/)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5109/console
[build-osuosl-aix71-ppc64-2](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-2/)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5110/console
[test-osuosl-aix715-ppc64-4](https://ci.adoptopenjdk.net/computer/test-osuosl-aix715-ppc64-4/)

**Comment by Haroon-Khel** [comment] 2022-07-07 09:46
The grinders ran the test for 5 iterations. Only the 1st iteration failed due to time out on test-osuosl-aix715-ppc64-1 and test-osuosl-aix715-ppc64-4, the test passed. Seems intermittent as it did not fail again on test-osuosl-aix715-ppc64-3

**Comment by aixtools** [comment] 2022-07-07 14:10
I looked at the stderr output - and I cannot help thinking -
- is it java11 only?
- some code optimization for thread handling - is too optimized (see a lot of `- waiting to re-lock in wait()`

**Comment by aixtools** [comment] 2022-07-14 18:04
- Want to comment: the success is on AIX 7.1 TL4, and failure on AIX 7.1 TL5 - so we may be looking at a threading bug in AIX 7.1 TL5 (as one possible explanation).
- what I also notice: when I rebuilt test-osuosl-aix715-ppc64-2 I did NOT install AIX 7.1 TL5 SP9 (as the other three are) - but it is still on AIX 7.1 TL5 SP6 - again, could be a RTE (e.g., thread library) difference
- test-osuosl-aix72-ppc64-X are at AIX 7.2 TL4 SP2, for another check try build-osuosl-aix72-ppc64-1 (AIX 7.2 TL2 SP4)
- @Haroon-Khel : can you run the build-*aix72* and see if that passes, or not?

**Comment by aixtools** [comment] 2022-08-01 13:40
Did this _go away_?

**Comment by aixtools** [comment] 2022-11-04 10:20
- I suggest closing this as no longer relevant.

- OR, updated with a URL that can reproduce the test on one system - and can be simply modified to run on a different target.

**Comment by aixtools** [comment] 2022-11-09 17:53
URL that does the test needed, or close?

**Comment by aixtools** [comment] 2023-07-21 10:22
As AIX 7.1 is no longer being used - I'm going to risk closing this as **No longer relevant**.

IMHO: if the issue comes up again - on a current system - a new issue should be opened.

**Closed by aixtools** 2023-07-21 10:22 UTC
Labels: os:aix, provider:osuosl, testFail
