### ISSUE TITLE
(large j9core.dmp) test-osuosl-aix72-ppc64-1: error: copy-fd: write returned There is not enough space in the file system. + libXrender problem

### ISSUE THREAD

**Issue by lumpfish** [adoptium/infrastructure#1772] opened 2020-12-21 11:13 UTC
Test buids are failing on test-osuosl-aix72-ppc64-1 with out of space messages - e.g. https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_j9_extended.system_ppc64_aix/83/console
```
Running on test-osuosl-aix72-ppc64-1 in /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix
[Pipeline] {
[Pipeline] checkout
The recommended git tool is: git
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
ERROR: Workspace has a .git repository, but it appears to be corrupt.
hudson.plugins.git.GitException: Command "git rev-parse --is-inside-work-tree" returned status code 128:
stdout: 
stderr: fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2380)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2376)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1923)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1935)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.hasGitRepo(CliGitAPIImpl.java:347)
	at hudson.plugins.git.GitAPI.hasGitRepo(GitAPI.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:936)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:909)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:860)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
Cloning the remote Git repository
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/openjdk-tests
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:997)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:752)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-osuosl-aix72-ppc64-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor467.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy416.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1219)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$541/000000000000000000.run(Unknown Source)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:823)
Caused by: hudson.plugins.git.GitException: Command "git init /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/openjdk-tests" returned status code 128:
stdout: 
stderr: error: copy-fd: write returned There is not enough space in the file system.
fatal: cannot copy '/opt/freeware/share/git-core/templates/description' to '/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/openjdk-tests/.git/description': There is not enough space in the file system.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2380)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2376)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1923)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:995)
	... 11 more
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Cloning repository https://github.com/AdoptOpenJDK/openjdk-tests.git
 > git init /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/openjdk-tests # timeout=10
ERROR: Error cloning remote repo 'origin'
Finished: FAILURE

REST API
Jenkins 2.263.1
```

**Comment by Haroon-Khel** [comment] 2020-12-21 12:30
Cleared up about 70g from test outputs

**Comment by sxa** [comment] 2020-12-21 14:39
> Cleared up about 70g from test outputs

That's a lot given that the tests should clean up their own directories under `workspace` - was that stuff from somewhere else on the file system?

**Comment by Haroon-Khel** [comment] 2020-12-21 15:04
It was in `test_output_16083391022048` in `workspace/Test_openjdk11_j9_extended.functional_ppc64_aix/openjdk-tests/TKG`.

**Comment by andrew-m-leonard** [comment] 2020-12-23 09:34
@sxa Impressive !

**Comment by andrew-m-leonard** [comment] 2020-12-23 09:37
Not just one test:
```
0	CDSAdaptorTest_0
228K	CallerSensitiveGetCallerClassTest_0
348K	ContendedFieldsTests_90_0
348K	ContendedFieldsTests_90_1
348K	ContendedFieldsTests_90_2
348K	ContendedFieldsTests_90_3
224K	HashConsistency_0
232K	HashPerformance_0
224K	IllegalAccessProtectedMethodTest_0
224K	JCL_TEST_Java-Lang-Invoke_0
228K	MethodVisibilityTests_0
552K	SoftmxRASTest1_2
476K	SoftmxRASTest2_2
224K	StackWalkerTestJava10_0
284K	StackWalkerTest_0
284K	StackWalkerTest_1
224K	StaticAccessChecks-IllegalAccessDeny_0
224K	StaticAccessChecks-IllegalAccessPermit_0
228K	TestAttachAPIEnabling_0
424K	TestAttachAPI_0
228K	TestClassLoaderFindResource_0
316K	TestFileLocking_0
224K	TestGCClassWithStaticRetransformInBalanced_0
232K	TestJava9AttachAPI_0
264K	TestJcmd_0
232K	TestJmap_0
244K	TestJps_0
232K	TestJstack_0
224K	TestJstat_0
224K	TestManagementAgent_0
224K	TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_0
224K	TestSoftMxCallBackExtend_1
224K	TestSoftMxCallBackOOM_1
232K	TestSunAttachClasses_0
2.8M	TestTargetResult
0	ThreadRegressionTests_3
0	ThreadRegressionTests_4
232K	UnreflectTests_0
360K	VarHandleInvokerTest_0
368K	VarHandleInvokerTest_1
1.4M	VarHandle_0
348K	View-BE-OffHeap_0
504K	View-BE-OnHeap_0
348K	View-LE-OffHeap_0
504K	View-LE-OnHeap_0
536K	VmArgumentTests_0
2.9G	cmdLineTest_J9test_extended_0
0	cmdLineTest_J9test_native_0
0	cmdLineTester_EnableAssertionStatusTest_0
0	cmdLineTester_LazyClassLoading_1
0	cmdLineTester_PageAlignDirectMemory_0
0	cmdLineTester_SystemPropertiesTest_aix_0
0	cmdLineTester_bootStrapStaticVerify_0
18G	cmdLineTester_classesdbgddrext_1
18G	cmdLineTester_classesdbgddrext_aix_1
0	cmdLineTester_decompilationTests_nongold_2
0	cmdLineTester_decompilationTests_nongold_3
0	cmdLineTester_doProtectedAccessCheck_0
0	cmdLineTester_dscr_0
0	cmdLineTester_fastClassHashTable_0
3.5M	cmdLineTester_fieldwatchtests_0
0	cmdLineTester_getCallerClassTests_0
0	cmdLineTester_ignoreunrecognizedvmoptions_0
0	cmdLineTester_ignoreunrecognizedxxcolonoptions_0
0	cmdLineTester_javaAssertions_0
0	cmdLineTester_jvmtitests_hcr_OSRG_nongold_2
0	cmdLineTester_jvmtitests_hcr_OSRG_nongold_3
0	cmdLineTester_jvmtitests_hcr_OSRG_nongold_4
0	cmdLineTester_locales_0
0	cmdLineTester_lockWordAlignment_Object_Standard_0
0	cmdLineTester_lockWordAlignment_Object_d_0
0	cmdLineTester_lockWordAlignment_Object_i_0
0	cmdLineTester_lockWordAlignment_Object_ii_0
0	cmdLineTester_lockWordAlignment_Object_iii_0
18G	cmdLineTester_modularityddrtests_1
0	cmdLineTester_reflectCache_0
0	cmdLineTester_shareClassesBadStackMap_0
224K	constantPoolTagTests_0
224K	defineModuleAsClassTest_0
224K	gcNotificationTest_Balanced_0
224K	gcNotificationTest_Balanced_1
224K	gcNotificationTest_GenCon_0
224K	gcNotificationTest_GenCon_1
224K	gcNotificationTest_Metronome_0
224K	gcNotificationTest_Metronome_1
224K	gcNotificationTest_OptAvgpause_0
224K	gcNotificationTest_OptAvgpause_1
224K	gcNotificationTest_Optthruput_0
224K	gcNotificationTest_Optthruput_1
2.0G	gcPolicyNogcOOMTest_0
0	gcPolicyNogcOOMTest_1
224K	gcPolicyNogcTest_0
224K	gcPolicyNogcTest_1
0	j9vmClassUnloading_2
0	j9vmClassUnloading_4
0	j9vmClassUnloading_5
224K	jit_hw_0
224K	jit_hw_1
224K	jit_hw_2
232K	jniOnLoadExceptions_1
232K	jniOnLoadExceptions_3
232K	jniOnLoadExceptions_4
224K	jsr292BootstrapTest_0
224K	jsr292BootstrapTests_special_0
1.6M	jsr292Test_0
1.6M	jsr292Test_1
1.5M	jsr292Test_JitCount0_0
1.2M	jsr292Test_Lookup_0
1.2M	jsr292Test_Lookup_1
1.2M	jsr292Test_Lookup_JitCount0_0
352K	jsr292_InDynTest_0
352K	jsr292_InDynTest_1
2.5M	jsr292_MethodHandleAPI_Test_0
2.5M	jsr292_MethodHandleAPI_Test_JitCount1_0
232K	memoryCategories_0
224K	memoryMXBeanShutdownTest_0
248K	regressionBucketDefault_1
224K	testClassLoadingDelegation_0

260K	testContendedClassLoading_0
224K	testCpuUtilization_testMxBean_0
224K	testCpuUtilization_testSingleCpuLoadObject_0
1.6G	testDDRExtJunit_CollisionResilientHashtable_0
1.5G	testDDRExtJunit_FindExtThread_0
1.5G	testDDRExtJunit_MonitorsAndDeadlock1_1
1.5G	testDDRExtJunit_MonitorsAndDeadlock2_1
1.5G	testDDRExtJunit_MonitorsAndDeadlock3_1
1.5G	testDDRExtJunit_MonitorsAndDeadlock4_1
1.5G	testDDRExtJunit_MonitorsAndDeadlock5_1
1.5G	testDDRExtJunit_MonitorsAndDeadlock6_1
1.6G	testDDRExtJunit_StackMap_0
1.5G	testDDRExt_Callsites_0
1.5G	testDDRExt_Class_0
1.6G	testDDRExt_General_0
1.5G	testDDRExt_JITExt_0
1.6G	testDDRExt_SharedClasses_0
964K	testDefaultDisclaimMemory_2
260K	testOpenJ9DiagnosticsMXBean_0
14G	testSCCMLTests2_1
1.7M	testSCCacheManagement_0
964K	testSoftMxDisclaimMemory_2
480K	testSoftMxDisclaimMemory_GC_2
964K	testSoftMxDisclaimMemory_LP64k_2
2.0G	testSoftMxLocal_2
2.0G	testSoftMxLocal_LP64k_2
484K	testSoftMxNotDisclaimMemory_2
252K	testSoftMxUserScenario_2
224K	testvmcheck_0
224K	testvmcheck_3
224K	testvmcheck_4
224K	testvmcheck_6
244K	threadMXBeanTestSuite1_2
244K	threadMXBeanTestSuite1_3
244K	threadMXBeanTestSuite1_6
244K	threadMXBeanTestSuite1_7
380K	threadMXBeanTestSuite2_2
380K	threadMXBeanTestSuite2_3
228K	threadMXBeanTestSuiteJava10_0
224K	threadMXBeanTimedParkTest_2
224K	threadMXBeanTimedParkTest_3
224K	threadMXBeanTimersTest_2
224K	threadMXBeanTimersTest_3
0	xlpTests_1
```

**Comment by andrew-m-leonard** [comment] 2020-12-23 09:39
Test_openjdk11_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/test_output_16086997302346/cmdLineTester_classesdbgddrext_1
-rw-r--r--    1 jenkins  staff    18566445080 Dec 23 00:48 j9core.dmp

**Comment by andrew-m-leonard** [comment] 2020-12-23 09:54
Raised: https://github.com/eclipse/openj9/issues/11537

**Comment by sxa** [comment] 2020-12-23 16:26
We have two issues here:
- The sytsem cannot load `libawt.so` correctly, as it picks up the `libXrender` from `/opt/freeware/lib` rather than the system `/usr/lib` (unclear so far why this may only be happening on the AIX7.2 system)
- The large core files chewing up 90Gb of disk space when the above probvlem occurs (which causes a crash that results in the code that would often clear up the core dumps to not be invoked)
Ultimately the first point above is the one we need to resolve

**Comment by sxa** [comment] 2020-12-23 16:34
Simple reproduction of the AWT problem:
- Download the JDK
- Create `awttest.java` with `public class awttest { public static void main(String[] a) { java.awt.Frame f = new java.awt.Frame("Hello world!"); f.setVisible(true); } }`
- javac awttest.java
- DISPLAY=:0 java awttest

**Comment by sxa** [comment] 2020-12-23 16:41
For now, I've renamed `/opt/freeware/lib/libXrender.a` to `libXrender.a-SXAMOVED1172` on test-osuosl-aix72-ppc64-1 and -2.

THIS IS NOT A SENSIBLE FINAL SOLUTION SO THIS ISSUE SHOULD NOT BE CLOSED

**Comment by sxa** [comment] 2020-12-23 17:14
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/91/ succeded on test-osuosl-aix72-ppc64-2 after the above change so we should be safe for tonight :-)

**Comment by sxa** [comment] 2020-12-24 14:26
Removing my assignment as I don't want to discourage others from investigating and providing a proper fix :-)

**Comment by Haroon-Khel** [comment] 2021-01-11 10:40
From what I have gathered, with help from Michael Felt, `/opt/freeware/lib/libXrender.a` comes from the package `libXrender-0.9.8-2waixX11.ppc`, which was installed `libXrender-0.9.8-2waixX11.ppc Mon Jul 29 11:11:06 CDT 2019`, as part of the playbooks, since a bunch of other packages where installed around that time. It seems to have been installed as a dependency to `libXrender-devel`
```
# yum deplist libXrender-devel
Finding dependencies: 
package: libXrender-devel.ppc 0.9.8-2waixX11
  dependency: libXrender = 0.9.8-2waixX11
   provider: libXrender.ppc 0.9.8-2waixX11
```
However rpm disagrees (though I assume yum and rpm track dependencies differently?)
```
# rpm -q --whatrequires libXrender-0.9.8-2waixX11.ppc
no package requires libXrender-0.9.8-2waixX11.ppc
```

**Comment by aixtools** [comment] 2021-03-23 08:07
OK - looking on test-ibm-aix71-ppc64-1
```
p159a01:/ # rpm -q --triggeredby libXrender
no package triggers libXrender

p159a01:/ # rpm -q --whatrequires libXrender
libXrender-devel-0.9.8-2waixX11.ppc
libXft-2.3.2-4waixX11.ppc

p159a01:/ # rpm -q --whatrequires libXrender-devel
no package requires libXrender-devel

p159a01:/ # rpm -q --whatrequires libXft
no package requires libXft
```

My quick quess is that ./configure needs an include file from `libXrender-devel` and then you run into issues such as:
```
p159a01:/ # rpm -q --requires libXrender-devel
libXrender = 0.9.8-2waixX11
pkg-config
renderproto >= 0.11.1
```

* My 'best guess` would be to remove libXrender, libXft and libXrender-devel and THEN try installing libXrender-devel using the --nodeps options. As happens in many of these - IBM provides a library, but not an include file.
* If ever there was a reason for vendor_files (that need maintaining!) I would be looking at an archive or geturl of the specific include file I need - to match the library IBM provides.
* `  /usr/lpp/X11/lib/R7/libXrender.a            X11.base.lib          File`

**Comment by sxa** [comment] 2021-06-09 16:32
@lumpfish saw the libXrender problem today on test-osuosl-aix71-ppc64-1 so it's definitely not specific to AIX 7.2. I have made the same change described earlier at https://github.com/adoptium/infrastructure/issues/1772#issuecomment-750379738

**Comment by sxa** [comment] 2021-07-05 11:09
Moving to July - we need to get this driven to a conclusion

**Comment by aixtools** [comment] 2021-07-07 17:06
I would like to propose a `test` system without the rpm packages: libXrender, libXft, and libXrender-devel - to establish what files, if any, are actually (still) needed.

**Comment by aixtools** [comment] 2021-07-07 17:15
iirc: I mentioned this elsewhere, and setting a symbolic link to the target was not accepted as a solution. The preference was to add a define in the configure script, iirc, because AIX can provide Xrender.h.

Considering where it is - I would consider this a packaging bug myself.

```
root@p8-aix2-ojdk01:[/root]lslpp -w /usr/lpp/X11/include/X11/extensions/Xrender.h
  File                                        Fileset               Type
  ----------------------------------------------------------------------------
  /usr/lpp/X11/include/X11/extensions/Xrender.h
                                                 X11.adt.ext        File
```
Bug?: Actually, now - because now I see:

lrwxrwxrwx 1 bin bin 24 Jul  2  2020 /usr/include/X11 -> /usr/lpp/X11/include/X11

CFLAGS need to include -I/usr/include/X11 - or the code needs to `#include <X11/Xrender.h>`

**Comment by sxa** [comment] 2021-09-23 11:27
> I would like to propose a `test` system without the rpm packages: libXrender, libXft, and libXrender-devel - to establish what files, if any, are actually (still) needed.

Have we tried doing this on a new system? Would be good to verify whether we can have playbooks that do the correct setup and are verified as able to run builds + tests

**Comment by aixtools** [comment] 2021-09-25 11:38
afaik, this has not been tested yet. Just as you were getting to the point of building again - I left on vacation, and then got sick.

**Comment by aixtools** [comment] 2021-09-25 11:40
> 
> 
> > I would like to propose a `test` system without the rpm packages: libXrender, libXft, and libXrender-devel - to establish what files, if any, are actually (still) needed.
> 
> Have we tried doing this on a new system? Would be good to verify whether we can have playbooks that do the correct setup and are verified as able to run builds + tests

Further, considering the recent rebuild of ojdk03 - this could be tested there (AIX 7.2) rather than ojdk01 (an existing system config).

**Closed** 2021-10-01 09:25 UTC
Labels: os:aix, provider:osuosl, systemdown
