### ISSUE TITLE
centos7_docker_image_updater failing for riscv64 due to: docker denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3294] opened 2023-12-11 07:58 UTC
https://ci.adoptium.net/job/centos7_docker_image_updater/414/consoleFull
```
docker push index.docker.io/adoptopenjdk/ubuntu2004_build_image:linux-riscv64
The push refers to repository [docker.io/adoptopenjdk/ubuntu2004_build_image]
2e3013c2c1ee: Preparing
0403d5fa6b40: Preparing
c830df0cb617: Preparing
36f5e579bc71: Preparing
746375b35eef: Preparing
9be520fcb335: Preparing
f79d6a255c99: Preparing
8daca1af9922: Preparing
e419c1e23aba: Preparing
f79d6a255c99: Waiting
8daca1af9922: Waiting
e419c1e23aba: Waiting
9be520fcb335: Waiting
denied: requested access to the resource is denied
```

**Comment by sxa** [comment] 2023-12-11 10:21
Duplicate of the discussion in https://github.com/adoptium/infrastructure/issues/2753 - closing

**Closed by sxa** 2023-12-11 10:21 UTC
Labels: ansible, docker
