### ISSUE TITLE
Possible file system issue on test-osuosl-aix72-ppc64-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3038] opened 2023-04-19 07:52 UTC
- Please put the system name in the title of this issue.
- [test-osuosl-aix72-ppc64-1](https://ci.adoptium.net/computer/test-osuosl-aix72-ppc64-1)

- Link to any log file showing the problem:
https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk11u/job/jdk11u-release-aix-ppc64-temurin/5/console

- Please describe the issue:
```
23:13:08  find: cannot chdir to </tmp/.workdir.4456808.5505396_1> : Permission denied
23:13:08  find: cannot chdir to </tmp/.workdir.5112104.4456872_1> : Permission denied
23:13:08  find: cannot chdir to </tmp/.workdir.5505332.4849978_1> : Permission denied
23:13:08  find: cannot chdir to </tmp/.workdir.5898680.6095346_1> : Permission denied
23:13:08  find: cannot chdir to </tmp/9568612.mnt0> : Permission denied
23:13:08  find: cannot chdir to </tmp/errmbatch> : Permission denied
23:13:08  find: cannot chdir to </tmp/ibmsupt> : Permission denied
23:13:08  find: cannot chdir to </tmp/lost+found> : Permission denied
23:13:08  find: cannot chdir to </tmp/saved_errmbatch> : Permission denied
23:13:08  find: cannot chdir to </tmp/test14704751195605393183> : Permission denied
23:13:08  find: cannot chdir to </tmp/test18292979311362429356> : Permission denied
23:13:08  There are 0 sh-np files owned by jenkins in /tmp that I am going to remove...
23:13:08  find: cannot chdir to </tmp/.workdir.4456808.5505396_1> : Permission denied
23:13:08  find: cannot chdir to </tmp/.workdir.5112104.4456872_1> : Permission denied
23:13:08  find: cannot chdir to </tmp/.workdir.5505332.4849978_1> : Permission denied
23:13:08  find: cannot chdir to </tmp/.workdir.5898680.6095346_1> : Permission denied
23:13:08  find: cannot chdir to </tmp/9568612.mnt0> : Permission denied
23:13:08  find: cannot chdir to </tmp/errmbatch> : Permission denied
23:13:08  find: cannot chdir to </tmp/ibmsupt> : Permission denied
23:13:08  find: cannot chdir to </tmp/lost+found> : Permission denied
23:13:08  find: cannot chdir to </tmp/saved_errmbatch> : Permission denied
23:13:08  find: cannot chdir to </tmp/test14704751195605393183> : Permission denied
23:13:08  find: cannot chdir to </tmp/test18292979311362429356> : Permission denied
23:13:08  Using default /tmp for temporary files as /ramdisk0/build/tmp does not exist
```

**Comment by sxa** [comment] 2023-04-19 08:00
The permission errors are to be expected - something is running `find` over the shared `tmp` directory and it's got files owned by other users (mostly `root`) which aren't accessible to the jenkins user.

**Comment by aixtools** [comment] 2023-05-08 08:59
So, if I understand (read guess at what this issue is) - LTS builds need to move from AIX 7.1 to AIX 7.2 - and they are not yet working.

p.s. this is hostname alias adopt03.

**Comment by aixtools** [comment] 2023-05-09 09:30
I am reactivating this machine - to see if it acts up again.

**Comment by aixtools** [comment] 2023-05-10 11:25
Grinder look different - and I don't see any AIX systems atm. Did all go well? - it took off immediately yesterday.

**Comment by sxa** [comment] 2023-05-15 11:59
> Grinder look different

Hmmm - what's different with Grinder - I don't think it's changed recently (unless it has while I was on vacation!)
The issue with the freetype error occurred during a build job, not a test job, so Grinder likely won't show it anyway.

> LTS builds need to move from AIX 7.1 to AIX 7.2 - and they are not yet working.

It is building successfully on AIX 7.2 (We used that for the April releases of all release lines) just not on that particular system - https://ci.adoptium.net/computer/build-osuosl-aix72-ppc64-1 (adopt10) works ok.

**Comment by aixtools** [comment] 2023-05-15 12:05
Looks different - then it says how long I have been busy elsewhere.

Builds successfully: does that mean this can/should be closed?

**Comment by sxa** [comment] 2023-05-15 12:27
> Builds successfully: does that mean this can/should be closed?

No, because this issue was related to test-osuosl-aix72-ppc64-1 where I expect it's still failing. We didn't use that machine for the release builds last month.

**Comment by aixtools** [comment] 2023-05-15 13:11
If you can generate the test again, I'll look at it.

**Comment by sxa** [comment] 2023-05-15 15:36
Sure - I've queued up another run of the above job with `NODE_LABEL` set to the specific machine at https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk11u/job/jdk11u-release-aix-ppc64-temurin/7/console although it's queued up behind a test job at the moment.

While I haven't tried it for this problem, ity should be possible to reproduce using the guide in https://github.com/adoptium/infrastructure/blob/master/FAQ.md#how-do-i-replicate-a-build-failure too

**Comment by aixtools** [comment] 2023-05-15 16:15
As the grinder job no longer exists - I have no idea which test to try and replicate.

**Comment by sxa** [comment] 2023-05-15 17:28
Same error as originally described is in the log in the previous comment so hopefully you can see that one.

**Comment by aixtools** [comment] 2023-05-15 20:17
The build system - where all worked has:
```
root@adopt10:[/root]lslpp -L | grep freet
  freetype2                    2.8-1    C     R    A free and portable font
  freetype2-devel              2.8-1    C     R    FreeType development libraries
```

While the failing system has:
```
root@p8-aix1-adopt03:[/root]lslpp -L | grep freet
  freetype2                 2.10.4-1    C     R    A free and portable font
  freetype2-devel           2.10.4-1    C     R    FreeType development libraries
root@p8-aix1-adopt03:[/root]
```

Deeper:
```
Name        : freetype2
Version     : 2.8
Release     : 1
Architecture: ppc
Install Date: Thu Jun 23 18:04:47 UTC 2022
Group       : System Environment/Libraries
Size        : 6835960
License     : BSD/GPL dual license
Signature   : (none)
Source RPM  : freetype2-2.8-1.src.rpm
Build Date  : Mon Mar 19 07:16:46 UTC 2018
```
And
```
root@p8-aix1-adopt03:[/root]rpm -qi freetype2
Name        : freetype2
Version     : 2.10.4
Release     : 1
Architecture: ppc
Install Date: Wed Sep 22 11:44:26 2021
Group       : System Environment/Libraries
Size        : 8465833
License     : BSD/GPL dual license
Signature   : (none)
Source RPM  : freetype2-2.10.4-1.src.rpm
Build Date  : Tue Aug 10 05:58:42 2021
Build Host  : pokndd10.pok.stglabs.ibm.com
Packager    : IBM AIX Toolbox <https://ibm.biz/AIXToolbox>
```

Notice that the `older` version (2.8) has a later build date than 2.10.

Good chance this is builddate/library issue. Such that the 2.2.10 doesn't match with the other libraries. Always been one of my RPM packaging concerns.

* Might just be some missing symbolic links:
Broken:

```
root@p8-aix1-adopt03:[/root]find /usr /opt -name libfreetype.\*
/usr/jdk-16.0.2+7/lib/libfreetype.so
/usr/jdk-17+18/lib/libfreetype.so
/usr/jdk-17.0.6+10/lib/libfreetype.so
/usr/lib/xorg/modules/fonts/libfreetype.so
/opt/freeware/lib/libfreetype.a
/opt/freeware/lib/libfreetype.la
root@p8-aix1-adopt03:[/root]ls -l /usr/lib/libfreet*
/usr/lib/libfreet* not found

```
Working:

```
root@adopt10:[/root]find /usr /opt -name libfreetype.\*
/usr/jdk-16.0.1+9/lib/libfreetype.so
/usr/jdk-17.0.4+7/lib/libfreetype.so
/usr/lib/libfreetype.a
/usr/lib/libfreetype.la
/usr/lib/xorg/modules/fonts/libfreetype.so
/opt/freeware/lib/libfreetype.a
/opt/freeware/lib/libfreetype.la
root@adopt10:[/root]ls -l /usr/lib/libfreet*
lrwxrwxrwx 1 root system 36 Jun 23  2022 /usr/lib/libfreetype.a -> ../../opt/freeware/lib/libfreetype.a
lrwxrwxrwx 1 root system 37 Jun 23  2022 /usr/lib/libfreetype.la -> ../../opt/freeware/lib/libfreetype.la
```

* The playbook: https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml on line 124 specifies freetype2-2.8.1 - for whatever reason.
* Other plays exclude freetype2 from updating to a later version.
* So, it ALSO seems this system has not been managed, i.e., followed the playbook specifications.

* However, going to try just adding symbolic links in /usr/lib to the actual libraries and see if that resolves the issue.

**Comment by aixtools** [comment] 2023-05-16 08:19
* Wasn't a file system issue. Needed to be freetype2-2.8 as specified in the playbooks. 
* Also tested latest version (2.12) - which also failed.
* See: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/233/console
```
10:13:39  checking for FREETYPE... yes
10:13:39  checking for freetype... yes (using pkg-config)
10:13:39  Using freetype: system
```

As far as this issue is concerned - imho, may be closed.

**Comment by sxa** [comment] 2023-05-16 12:16
So is adopt10 now working as the result of adjusting the symlinks? Is it now using the same or a different freetype version from adopt03?

**Comment by sxa** [comment] 2023-05-17 10:36
Build 233 completed the build phase with this output from the generated build:
```
09:40:55  =JAVA VERSION OUTPUT=
09:40:55  openjdk version "11.0.20-beta" 2023-07-18
09:40:55  OpenJDK Runtime Environment Temurin-11.0.20+2-202305160813 (build 11.0.20-beta+2-202305160813)
09:40:55  OpenJDK 64-Bit Server VM Temurin-11.0.20+2-202305160813 (build 11.0.20-beta+2-202305160813, mixed mode)
09:40:55  =/JAVA VERSION OUTPUT=
```
so I'm comfortable that it's now working as it should. I've kicked off another run at https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/235/console to see what stage it gets to. I suspect we'll get a lot of backlog on test jobs due to the fact we currently only have two AIX 7.2 machines labelled as capable of running tests, for which we'll need to start setting up more 7.2/7.3 systems to [replace some of the 7.1 ones](https://github.com/adoptium/infrastructure/issues/3030).

**Comment by aixtools** [comment] 2023-05-18 08:14
imho: this issue can be closed - as the original complaint - even if the title is not correct (maybe change that before closing) has been addressed.

There are likely other issues - but those should be addressed as a new ticket - not endlessly extending this one.

**Comment by sxa** [comment] 2023-05-18 09:57
Agreed - I was waiting for the output of the latest run to confirm. That one seems to have failed but only because it was looking for a machine with the sw.tool.docker tag on https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.external_ppc64_aix/7/console which shouldn't have been run on AIX.

On that basis I'm closing this - thanks for the fixes :-)

**Closed by sxa** 2023-05-18 09:57 UTC
Labels: os:aix, provider:osuosl, systemdown
