### ISSUE TITLE
System unavailable: trss-node

### ISSUE THREAD

**Issue by zdtsw** [adoptium/infrastructure#2822] opened 2022-11-17 07:45 UTC
- Please put the system name in the title of this issue.
https://ci.adoptopenjdk.net/computer/trss-node

- Link to any log file showing the problem:
https://ci.adoptopenjdk.net/job/TRSS_Code_Sync/14/console is hanging since 4th Nov
```
Still waiting to schedule task
‘[trss-node](https://ci.adoptopenjdk.net/computer/trss-node/)’ is offline
```
- Please describe the issue:
https://ci.adoptopenjdk.net/computer/trss-node/ show 
`trss-node offline: Disk space is too low. Only 0.237GB left on /tmp.`

**Comment by sxa** [comment] 2022-11-17 11:59
Duplicate of https://github.com/adoptium/infrastructure/issues/2781

**Closed by sxa** 2022-11-17 11:59 UTC
Labels: systemdown
