### ISSUE TITLE
System unavailable: https://ci.adoptopenjdk.net/label/hw.arch.riscv64/

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#1904] opened 2021-02-08 08:54 UTC
Both riscv64 nodes are down: https://ci.adoptopenjdk.net/label/hw.arch.riscv64/

**Comment by Willsparker** [comment] 2021-02-11 09:24
FYI (To anyone reading this): https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1612774510187200

**Comment by sxa** [comment] 2021-10-01 13:01
ping @gdams as the owner as two of the `test-gdams-` machines have been offline for several months now and particuarly we're now starting to run testing it would be good to have all available capacity online.

**Comment by sxa** [comment] 2022-06-24 09:12
Closing as duplicate of https://github.com/adoptium/infrastructure/issues/2080

**Closed** 2023-02-02 16:59 UTC
Labels: systemdown
