### ISSUE TITLE
extended.openjdk tests hit the 10hr timeout test-docker-ubuntu2110-armv8l-1 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2923] opened 2023-02-03 18:48 UTC
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? extended.openjdk
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure
  - https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/97/
- **Hyperlink** to re-run in Grinder: 
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? test-docker-ubuntu2204-armv8l-2 (job takes 6hrs32min)
- Which machine(s) does it fail on? test-docker-ubuntu2110-armv8l-1 

Any other details:
There are 5 test cases that fail (out of the 13,939 in extended.openjdk).
[java/net/httpclient/ManyRequestsLegacy.java.ManyRequestsLegacy](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/97/testReport/junit/java_net_httpclient_ManyRequestsLegacy/java/ManyRequestsLegacy/)
[jdk/incubator/vector/Byte256VectorTests.java.Byte256VectorTests](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/97/testReport/junit/jdk_incubator_vector_Byte256VectorTests/java/Byte256VectorTests/)
[jdk/incubator/vector/Byte512VectorTests.java.Byte512VectorTests](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/97/testReport/junit/jdk_incubator_vector_Byte512VectorTests/java/Byte512VectorTests/)
[jdk/incubator/vector/Byte64VectorLoadStoreTests.java.Byte64VectorLoadStoreTests](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/97/testReport/junit/jdk_incubator_vector_Byte64VectorLoadStoreTests/java/Byte64VectorLoadStoreTests/)
[jdk/incubator/vector/Byte64VectorTests.java.Byte64VectorTests](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/97/testReport/junit/jdk_incubator_vector_Byte64VectorTests/java/Byte64VectorTests/)

These tests pass on  test-docker-ubuntu2204-armv8l-2, so these failures 
`java.util.concurrent.CompletionException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake  ` and `Agent communication error: java.io.EOFException;`
are not helping get the job to complete within 10hrs.  Presumably if these are understood and fixed, we may see the runs complete within the 10hrs.

**Comment by sxa** [comment] 2023-02-06 11:05
Re-running with 50 hour timeout on the GA build at https://ci.adoptopenjdk.net/job/Grinder/ to see if it's reproducible and how much over the limit it is.
NOTE: There should be no performance difference between test-docker-ubuntu2110-armv8l-1 and test-docker-ubuntu2204-armv8l-2 and they're on the same physical host.

**Comment by sxa** [comment] 2023-02-08 11:24
https://ci.adoptopenjdk.net/job/Grinder/6549/ completed in 9h18 on https://ci.adoptopenjdk.net/label/test-docker-ubuntu2110-armv8l-1 so it's close to 10h and may be affected when other things are running on the host.

Running the following on the two systems to see how they perform as another data point:
- https://ci.adoptopenjdk.net/job/Grinder/6583/ (ubuntu2110)
- https://ci.adoptopenjdk.net/job/Grinder/6584/ (ubuntu2204)

**Comment by sxa** [comment] 2023-03-08 16:00
ubuntu2110 took 9h30
ubuntu2204 took 6h30
Both passed all13,931 tests
Both were started at pretty much the same time (to within a minute) but one of them just seemed to get though everything a bit more slowly:
[times.2583.gz](https://github.com/adoptium/infrastructure/files/10922472/times.2583.gz)
[times.6583.gz](https://github.com/adoptium/infrastructure/files/10922473/times.6583.gz)

**Comment by sxa** [comment] 2023-04-03 12:23
Duplicate of https://github.com/adoptium/infrastructure/issues/2923#issuecomment-1460405723

**Closed by sxa** 2023-04-03 12:23 UTC
Labels: docker, testFail
