### ISSUE TITLE
Clear up 'offline' agents in jenkins

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2879] opened 2023-01-11 12:43 UTC
We have over 70 systems which are defined in jenkins but are not currently online. We should go through them and see if they are still required, available, and needed and if not remove them. I suspect that if jenkins is expecting them to be online then they are using resources on the server as it tries to reconnect to them, which will likely have contributed to the recent issues reported in https://github.com/adoptium/infrastructure/issues/2875:

I suspect the test-docker ones can be easily identified and resolved so I'm listing them first - the others may require a bit more investigation:

(This list was generated by @steelhead31):

- [ ] test-docker-alma8-aarch64-1
- [ ] test-docker-alpine311-aarch64-1
- [ ] test-docker-alpine312-aarch64-1
- [ ] test-docker-alpine313-aarch64-1
- [ ] test-docker-alpine314-aarch64-1
- [ ] test-docker-alpine314-aarch64-2
- [ ] test-docker-alpine315-aarch64-1
- [ ] test-docker-fedora33-ppc64le-1
- [ ] test-docker-fedora35-aarch64-1
- [ ] test-docker-fedora35-armv8l-1
- [ ] test-docker-fedora36-aarch64-1
- [ ] test-docker-rocky9-aarch64-1
- [ ] test-docker-ubi9-aarch64-1
- [ ] test-docker-ubuntu1804-aarch64-1
- [ ] test-docker-ubuntu1804-ppc64le-1
- [ ] test-docker-ubuntu2004-aarch64-1
- [ ] test-docker-ubuntu2004-armv8l-2
- [ ] test-docker-ubuntu2004-armv8l-3
- [ ] test-docker-ubuntu2004-ppc64le-1
- [ ] test-docker-ubuntu2010-armv8l-2
- [ ] test-docker-ubuntu2010-ppc64le-1
- [ ] test-docker-ubuntu2204-armv8l-3

And the ones which aren't `test-docker`:

- [ ] build-alibaba-ubuntu1804-armv8-1
- [ ] build-alibaba-ubuntu1804-armv8-2
- [ ] build-azure-win2012r2-x64-3-sxa
- [ ] build-docker-ubuntu2004-armv7l-1
- [ ] build-equinix-centos8-armv8-1
- [ ] build-equinix-ubuntu1604-armv7l-2
- [ ] build-equinix_esxi-solaris10-x64-1-NEW
- [ ] build-marist-rhel79-s390x-1
- [ ] build-osuosl-ubuntu2204-aarch64-1
- [ ] build-scaleway-ubuntu1604-x64-1
- [ ] build-spearhead-freebsd12-x64-1
- [ ] build-sxa-centos7-aarch64-1
- [ ] build-sxa-ubuntu1804-armv7l
- [ ] docker-aws-ubuntu1604-x64-0
- [ ] docker-aws-ubuntu1604-x64-1
- [ ] docker-aws-ubuntu1604-x64-2
- [ ] docker-equinix-ubuntu2004-armv8-1
- [ ] docker-packet-ubuntu2004-armv8-1f33
- [ ] docker-packet-ubuntu2004-armv8-1u1804
- [ ] docker-packet-ubuntu2004-armv8-1u2004
- [ ] docker-packet-ubuntu2004-armv8-1u2010
- [ ] infra-aws-ubuntu1804-x64-1
- [ ] test-aahlenst-armv7-raspbian-pi4-1
- [ ] test-aahlenst-armv7-raspbian-pi4-2
- [ ] test-alibaba-debian-riscv64-1
- [ ] test-alibaba-ubuntu1804-armv8-1
- [ ] test-alibaba-ubuntu1804-armv8-2
- [ ] test-aws-ubuntu1804-armv8-1
- [ ] test-aws-ubuntu2004-x64-1
- [ ] test-azure-win11-aarch64-1
- [ ] test-equinix-ubuntu1604-x64-1
- [ ] test-equinix-win2012r2-x64-1
- [ ] test-equinix_esxi-solaris10-x64-1-NEW
- [ ] test-gdams-debian10-riscv64-1
- [ ] test-gdams-debian10-riscv64-2
- [ ] test-ibmcloud-rhel6-x64-1
- [ ] test-macstadium-macos1014-x64-4
- [ ] test-marist-ubuntu1804-s390x-1
- [ ] test-nine-macos1015-x64-1
- [ ] test-nine-macos1015-x64-2
- [ ] test-osuosl-ubuntu1604-ppc64le-3
- [ ] test-osuosl-ubuntu1604-ppc64le-4
- [ ] test-packet-ubuntu1604-armv8-2-OFF
- [ ] test-plctlab-ubuntu2104-riscv64-3
- [ ] test-plctlab-ubuntu2104-riscv64-5
- [ ] test-sxa-armv7-raspbian-pi4
- [ ] test-sxa-armv7l-ubuntu2004-odroid-2
- [ ] test-sxa-fedora-riscv-1
- [ ] test-sxa-ubuntu-aarch64-jetson
- [ ] test-sxa-ubuntu2004-aarch64-odroid
- [ ] test-sxamb-armv7l-raspbian-pi4-1
- [ ] test-will-debian-riscv-1

**Comment by steelhead31** [comment] 2023-01-30 14:01
|azurebuildagentc16b00                |Offline|Empty                                             |Empty|java                                                           |  
|-------------------------------------|-------|--------------------------------------------------|-----|---------------------------------------------------------------|  
|build-alibaba-ubuntu1804-armv8-1     |Offline|119.8.164.219                                     |22   |Empty                                                          |  
|build-alibaba-ubuntu1804-armv8-2     |Offline|159.138.100.163                                   |22   |Empty                                                          |  
|build-azure-win2012r2-x64-3-sxa      |Offline|Empty                                             |Empty|Empty                                                          |  
|build-azure-win2012r2-x64-4-sxa      |Offline|Empty                                             |Empty|Empty                                                          |  
|build-docker-ubuntu2004-armv7l-1     |Offline|147.75.35.203                                     |2321 |Empty                                                          |  
|build-equinix-centos8-armv8-1        |Offline|139.178.86.243                                    |22   |Empty                                                          |  
|build-equinix-ubuntu1604-armv7l-2    |Offline|Empty                                             |Empty|Empty                                                          |  
|build-marist-rhel79-s390x-1          |Offline|148.100.75.212                                    |22   |/usr/lib/jvm/jdk-17/bin/java                                   |  
|build-osuosl-ubuntu2204-aarch64-1    |Offline|140.211.169.57                                    |22   |Empty                                                          |  
|build-packet\_esxi-solaris10u11-x64-1 |Offline|147.75.85.212                                     |22   |Empty                                                          |  
|build-scaleway-ubuntu1604-x64-1      |Offline|51.15.46.107                                      |22   |Empty                                                          |  
|build-spearhead-freebsd12-x64-1      |Offline|185.131.222.224                                   |22   |/usr/local/openjdk8/bin/java                                   |  
|build-sxa-centos7-aarch64-1          |Offline|Empty                                             |Empty|Empty                                                          |  
|build-sxa-ubuntu1804-armv7l          |Offline|Empty                                             |Empty|Empty                                                          |  
|test-aahlenst-armv7-raspbian-pi4-1   |Offline|Empty                                             |Empty|Empty                                                          |  
|test-aahlenst-armv7-raspbian-pi4-2   |Offline|Empty                                             |Empty|Empty                                                          |  
|test-alibaba-debian-riscv64-1        |Offline|Empty                                             |Empty|Empty                                                          |  
|test-alibaba-ubuntu1804-armv8-1      |Offline|119.8.166.104                                     |22   |Empty                                                          |  
|test-alibaba-ubuntu1804-armv8-2      |Offline|114.119.175.125                                   |22   |Empty                                                          |  
|test-aws-ubuntu1804-armv8-1          |Offline|ec2-34-243-202-254.eu-west-1.compute.amazonaws.com|22   |Empty                                                          |  
|test-aws-ubuntu2004-x64-1            |Offline|34.241.242.10                                     |22   |Empty                                                          |  
|test-azure-win11-aarch64-1           |Offline|Empty                                             |Empty|Empty                                                          |  
|test-azure-win2012r2-x64-1           |Offline|Empty                                             |Empty|Empty                                                          |  
|test-azure-win2016-x64-1             |Offline|Empty                                             |Empty|Empty                                                          |  
|test-docker-alpine313-aarch64-1      |Offline|147.75.35.203                                     |2223 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-alpine314-aarch64-1      |Offline|147.75.35.203                                     |2224 |/usr/lib/jvm/java-1.8-openjdk/bin/java                         |  
|test-docker-centos8-x64-2            |Offline|145.40.113.173                                    |2229 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-debian11-ppc64le-1       |Offline|20.61.136.212                                     |2211 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-debian11-ppc64le-2       |Offline|20.61.136.212                                     |2212 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-fedora33-ppc64le-1       |Offline|140.211.168.214                                   |2227 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-fedora35-armv8l-1        |Offline|147.75.35.203                                     |2235 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-fedora35-x64-1           |Offline|145.40.114.58                                     |2225 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-rocky9-aarch64-1         |Offline|139.178.86.243                                    |2227 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubi8-armv8-1             |Offline|139.178.86.243                                    |2247 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubi8-x64-2               |Offline|145.40.113.173                                    |2226 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubi9-aarch64-1           |Offline|139.178.86.243                                    |2229 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubuntu1804-aarch64-1     |Offline|139.178.86.243                                    |2223 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubuntu1804-armv8l-2      |Offline|147.75.35.203                                     |2230 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu1804-ppc64le-1     |Offline|140.211.168.214                                   |2223 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2004-armv8l-2      |Offline|147.75.35.203                                     |2226 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2004-armv8l-3      |Offline|147.75.35.203                                     |2232 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2010-armv8l-2      |Offline|147.75.35.203                                     |2231 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2010-ppc64le-1     |Offline|140.211.168.214                                   |2225 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2204-armv8l-3      |Offline|Empty                                             |Empty|Empty                                                          |  
|test-docker-ubuntu2204-ppc64le-1     |Offline|20.61.136.212                                     |2213 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubuntu2204-ppc64le-2     |Offline|20.61.136.212                                     |2214 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-equinix-ubuntu1604-x64-1        |Offline|147.75.204.239                                    |22   |Empty                                                          |  
|test-equinix-win2012r2-x64-1         |Offline|Empty                                             |Empty|Empty                                                          |  
|test-gdams-debian10-riscv64-1        |Offline|gdams.ddns.net                                    |22   |/home/jenkins/jdk-11.0.10+9/bin/java                           |  
|test-gdams-debian10-riscv64-2        |Offline|gdams.ddns.net                                    |2222 |/home/jenkins/jdk-11.0.8+10/bin/java                           |  
|test-ibmcloud-rhel6-x64-1            |Offline|169.48.4.140                                      |22   |Empty                                                          |  
|test-ibmcloud-win2012r2-x64-1        |Offline|Empty                                             |Empty|Empty                                                          |  
|test-macstadium-macos1014-x64-4      |Offline|207.254.71.202                                    |22   |/Library/Java/JavaVirtualMachines/jdk-17/Contents/Home/bin/java|  
|test-marist-rhel7-s390x-2            |Offline|148.100.74.92                                     |22   |/usr/lib/jvm/jdk-11/bin/java                                   |  
|test-marist-sles15-s390x-2           |Offline|148.100.74.154                                    |22   |/usr/lib/jvm/jdk-11/bin/java                                   |  
|test-marist-ubuntu1804-s390x-1       |Offline|148.100.113.30                                    |22   |/usr/lib/jvm/jdk-13.0.1+9/bin/java                             |  
|test-nine-macos1015-x64-1            |Offline|2a02:418:3001:40::10                              |22   |Empty                                                          |  
|test-nine-macos1015-x64-2            |Offline|2a02:418:3001:40::11                              |22   |Empty                                                          |  
|test-osuosl-aix72-ppc64-4            |Offline|140.211.9.166                                     |22   |/usr/java8\_64/bin/java                                         |  
|test-osuosl-ubuntu1604-ppc64le-3     |Offline|140.211.168.248                                   |22   |Empty                                                          |  
|test-osuosl-ubuntu1604-ppc64le-4     |Offline|140.211.168.239                                   |22   |Empty                                                          |  
|test-packet-ubuntu1604-armv8-2-OFF   |Offline|147.75.193.234                                    |22   |Empty                                                          |  
|test-plctlab-ubuntu2104-riscv64-3    |Offline|Empty                                             |Empty|Empty                                                          |  
|test-plctlab-ubuntu2104-riscv64-5    |Offline|Empty                                             |Empty|Empty                                                          |  
|test-sxa-armv7-raspbian-pi4          |Offline|Empty                                             |Empty|Empty                                                          |  
|test-sxa-debian11-riscv64-1          |Offline|Empty                                             |Empty|Empty                                                          |  
|test-sxa-fedora-riscv-1              |Offline|Empty                                             |Empty|Empty                                                          |  
|test-sxa-ubuntu-aarch64-jetson       |Offline|Empty                                             |Empty|Empty                                                          |  
|test-sxa-ubuntu2004-aarch64-odroid   |Offline|Empty                                             |Empty|Empty                                                          |  
|test-sxamb-armv7l-raspbian-pi4-1     |Offline|ssh.adoptpi3.hostedpi.com                         |5065 |/usr/lib/jvm/jdk-11/bin/java                                   |  
|test-will-debian-riscv-1             |Offline|Empty                                             |Empty|Empty                                                          |  
|build-docker-ubuntu2004-armv7l-1     |Offline|147.75.35.203                                     |2321 |Empty                                                          |  
|docker-aws-ubuntu1604-x64-0          |Offline|54.154.142.31                                     |22   |/usr/lib/jvm/jdk8u242-b08/bin/java                             |  
|docker-aws-ubuntu1604-x64-1          |Offline|34.253.28.27                                      |22   |/usr/lib/jvm/jdk8u242-b08/bin/java                             |  
|docker-aws-ubuntu1604-x64-2          |Offline|34.250.61.39                                      |22   |/usr/lib/jvm/jdk8u242-b08/bin/java                             |  
|docker-equinix-ubuntu2004-armv8-1    |Offline|139.178.82.146                                    |22   |Empty                                                          |  
|docker-packet-ubuntu2004-armv8-1f33  |Offline|139.178.82.146                                    |2227 |/usr/lib/jvm/jdk8/bin/java                                     |  
|docker-packet-ubuntu2004-armv8-1u1804|Offline|139.178.82.146                                    |2223 |/usr/lib/jvm/jdk8/bin/java                                     |  
|docker-packet-ubuntu2004-armv8-1u2004|Offline|139.178.82.146                                    |2224 |/usr/lib/jvm/jdk8/bin/java                                     |  
|docker-packet-ubuntu2004-armv8-1u2010|Offline|139.178.82.146                                    |2225 |/usr/lib/jvm/jdk8/bin/java                                     |  
|docker-skytap-ubuntu2004-ppc64le-1   |Offline|Empty                                             |Empty|Empty                                                          |  
|test-docker-alpine313-aarch64-1      |Offline|147.75.35.203                                     |2223 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-alpine314-aarch64-1      |Offline|147.75.35.203                                     |2224 |/usr/lib/jvm/java-1.8-openjdk/bin/java                         |  
|test-docker-centos8-x64-2            |Offline|145.40.113.173                                    |2229 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-debian11-ppc64le-1       |Offline|20.61.136.212                                     |2211 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-debian11-ppc64le-2       |Offline|20.61.136.212                                     |2212 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-fedora33-ppc64le-1       |Offline|140.211.168.214                                   |2227 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-fedora35-armv8l-1        |Offline|147.75.35.203                                     |2235 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-fedora35-x64-1           |Offline|145.40.114.58                                     |2225 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-rocky9-aarch64-1         |Offline|139.178.86.243                                    |2227 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubi8-armv8-1             |Offline|139.178.86.243                                    |2247 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubi8-x64-2               |Offline|145.40.113.173                                    |2226 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubi9-aarch64-1           |Offline|139.178.86.243                                    |2229 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubuntu1804-aarch64-1     |Offline|139.178.86.243                                    |2223 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubuntu1804-armv8l-2      |Offline|147.75.35.203                                     |2230 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu1804-ppc64le-1     |Offline|140.211.168.214                                   |2223 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2004-armv8l-2      |Offline|147.75.35.203                                     |2226 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2004-armv8l-3      |Offline|147.75.35.203                                     |2232 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2010-armv8l-2      |Offline|147.75.35.203                                     |2231 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2010-ppc64le-1     |Offline|140.211.168.214                                   |2225 |/usr/lib/jvm/jdk8/bin/java                                     |  
|test-docker-ubuntu2204-armv8l-3      |Offline|Empty                                             |Empty|Empty                                                          |  
|test-docker-ubuntu2204-ppc64le-1     |Offline|20.61.136.212                                     |2213 |/usr/lib/jvm/jdk17/bin/java                                    |  
|test-docker-ubuntu2204-ppc64le-2     |Offline|20.61.136.212                                     |2214 |/usr/lib/jvm/jdk17/bin/java                                    |

**Comment by steelhead31** [comment] 2023-01-30 16:28
The following have been removed..
Removed - test-docker-ubuntu2004-aarch64-1 - Duplicate Of test-docker-ubuntu2004-armv8-1
Removed - test-docker-fedora36-aarch64-1 - Duplicate Of test-docker-fedora36-armv8-1
Removed - test-docker-alma8-aarch64-1 - Incorrect Port Setup - Now on 2215
Removed - test-aahlenst-armv7-raspbian-pi4-1 - Not Online In > 3 years
Removed - test-aahlenst-armv7-raspbian-pi4-2 - Not Online In > 3 years
Removed - build-scaleway-ubuntu1604-x64-1 - Not Online In > 3 years
Removed - test-will-debian-riscv-1 - Not Online In > 3 years
Removed - test-alibaba-debian-riscv64-1 - Not Online In > 3 years
Removed - test-docker-ubi9-aarch64-1 - Container removed may be replaced in time, but until then..
Removed - test-docker-rocky9-aarch64-1 - Container removed may be replaced in time, but until then..
Removed - test-docker-ubuntu1804-aarch64-1 - Container removed may be replaced in time, but until then..
Removed - test-docker-ubuntu2204-armv8l-3 - Container removed may be replaced in time, but until then..

**Comment by steelhead31** [comment] 2023-01-31 08:49
Removed 11 defunct nodes, most other nodes are either deliberately offline, or are development ones, marked as temporarily offline. Nodes marked as temporarily offline, do not constantly reconnect and consume resources.

**Closed by steelhead31** 2023-01-31 08:49 UTC
Labels: critical, currency

**Comment by steelhead31** [comment] 2023-02-02 11:17
Also removed..

<table><tbody><tr><td>docker-equinix-ubuntu2004-armv8-1</td><td>Offline</td><td>139.178.82.146</td></tr><tr><td>docker-packet-ubuntu2004-armv8-1u1804</td><td>Offline</td><td>139.178.82.146</td></tr><tr><td>docker-packet-ubuntu2004-armv8-1u2004</td><td>Offline</td><td>139.178.82.146</td></tr><tr><td>docker-packet-ubuntu2004-armv8-1u2010</td><td>Offline</td><td>139.178.82.146</td></tr><tr><td>docker-packet-ubuntu2004-armv8-1f33</td><td>Offline</td><td>139.178.82.146</td></tr></tbody></table>

**Comment by steelhead31** [comment] 2023-02-03 12:40
Also removed
test-equinix-win2012r2-x64-1
