### ISSUE TITLE
build-azure-win2012r2-x64-1 J:\jenkins\workspace\build-scripts\release\create_installer_windows locked and can't be deleted

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2635] opened 2022-06-23 20:14 UTC
Installed jobs are failing on node build-azure-win2012r2-x64-1 due to an old install output locked file within J:\jenkins\workspace\build-scripts\release\create_installer_windows locked and can't be deleted

Please can this folder be deleted?

**Comment by andrew-m-leonard** [comment] 2022-06-24 08:36
I've disconnected until fixed: https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-1/

**Comment by Haroon-Khel** [comment] 2022-06-24 09:58
```
jenkins@bld-2012r2-1 /cygdrive/j
$ ls -la jenkins/workspace/build-scripts/release/create_installer_windows/wix/ReleaseDir/
total 88240
drwxrwxr-x+ 1 jenkins      None                 0 Jun 15 16:51 .
drwxrwxr-x+ 1 jenkins      None                 0 Jun 16 01:48 ..
-rw-r-----  1 Unknown+User Unknown+Group 90353664 Jun 15 16:51 OpenJDK8U-jdk_x64_windows_hotspot_2022-06-15-13-34.msi
```
Likely caused by this file. I'll see if I can determine the reason for the `Unknown+User Unknown+Group` before deleting it

**Comment by Haroon-Khel** [comment] 2022-06-24 12:09
As far as I can tell from googling, Cygwin must have hit an error when mapping windows accounts to posix accounts. Annoyingly I can't access the particular `create_installer job` which created that file as the job has expired. I'll delete the file for now

**Comment by Haroon-Khel** [comment] 2022-06-24 15:23
Took a while to delete the file. It was being used by a `java.exe` process which refused to die. The workspace should be 'deletable' now

**Comment by Haroon-Khel** [comment] 2022-06-29 20:42
Reopening as it occurred again. Looking into this

**Comment by andrew-m-leonard** [comment] 2022-07-01 11:01
Cleared, now re-running multiple times to try and force

**Comment by Haroon-Khel** [comment] 2022-07-01 11:02
> Took a while to delete the file. It was being used by a java.exe process which refused to die. The workspace should be 'deletable' now

That's interesting, last week the process that was locking the directory was a `java.exe` process, today's failure was caused by a leftover `sh.exe` process

**Comment by andrew-m-leonard** [comment] 2022-07-01 11:03
The only sh.exe I can see in the log is at the end:
```
[create_installer_windows] $ sh -xe C:\Users\jenkins.bld-2012r2-1\AppData\Local\Temp\jenkins3919534905505936000.sh
+ set -x
+ cd wix/SourceDir/
+ for FILEWITHEXTENSION in OpenJDK*-${PRODUCT_CATEGORY}*zip
+ FILENAME=OpenJDK-jdk_x64_windows_hotspot_2022-07-01-07-52.msi
+ cd 'J:\jenkins\workspace\build-scripts\release\create_installer_windows/wix/ReleaseDir/'
+ for FILE in *.msi
+ mv OpenJDK20-jdk_x64_windows_hotspot-20.0.0.0.4.msi OpenJDK-jdk_x64_windows_hotspot_2022-07-01-07-52.msi
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Archiving artifacts
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk-11.0.13+8" on the node "build-azure-win2012r2-x64-1"
[Slack Notifications] found #19139 as previous completed, non-aborted build
Finished: SUCCESS

```

**Comment by Haroon-Khel** [comment] 2022-07-14 15:40
@sxa ref https://github.com/adoptium/infrastructure/issues/2662#issuecomment-1184587728
Do you think you could add leftover `jcmd` processes to your ProcessCheck job? I see that the job currently stops `java`, `xvfb` and `revokeall` processes

**Comment by sxa** [comment] 2022-07-14 15:54
> @sxa ref [#2662 (comment)](https://github.com/adoptium/infrastructure/issues/2662#issuecomment-1184587728) Do you think you could add leftover `jcmd` processes to your ProcessCheck job? I see that the job currently stops `java`, `xvfb` and `revokeall` processes

Done, although had you already cleared it up? https://ci.adoptopenjdk.net/view/Tooling/job/SXA-processCheck/label=test-azure-win2012r2-x64-1/304/console didn't find any ...

**Comment by Haroon-Khel** [comment] 2022-07-14 16:09
Yep. I cant see the `jcmd` processes on the machine anymore. Thanks

**Comment by sxa** [comment] 2022-07-15 10:45
Closing as this should be fixed more reliably by including `jcmd` in the [SXA-ProcessCheck job](https://ci.adoptopenjdk.net/view/Tooling/job/SXA-processCheck/) - we can reopen again later if required.

**Closed by sxa** 2022-07-15 10:45 UTC
Labels: os:windows, ansible, arch:x64, testFail, provider:azure
