### ISSUE TITLE
Access request for <rtoyonag>

### ISSUE THREAD

**Issue by roberttoyonaga** [adoptium/infrastructure#3381] opened 2024-02-12 13:09 UTC
**NOTE: THIS ISSUE SHOULD NOT BE CLOSED BY THE ORIGINATOR IF ACCESS IS GRANTED**.
When the access is no longer needed please add a comment and a member
of the infrastructure team will revoke it and close the issue.

Required access level (Delete as appropriate). Note that you should only
request the minimum level that is required to solve your problem

- [x] Non-privileged
- [ ] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed:
https://ci.adoptium.net/computer/test-azure-win2016-x64-1/

Please explain why you need this access including whether it is a temporary or permanent request:
Temporary request to investigate jdk17 windows 32 bit issues with JFR tests https://github.com/adoptium/aqa-tests/issues/4352#issuecomment-1915239392 
https://ci.adoptium.net/view/Test_grinder/job/Grinder/8771/testReport/

**Comment by sxa** [comment] 2024-02-14 09:15
Hi @roberttoyonaga - can you clarify why Administrative level access is required for this? In general our tests run as a normal user without special privileges so I would expect that any debugging of failures would not require administrative access.

**Comment by sxa** [comment] 2024-02-14 09:19
@andrew-m-leonard It looks like we've got three machines assigned for reproducible build work - are they still required?

- adopt-bld-repro1 at 20.77.116.89
- adopt-bld-repro2 at 20.68.163.224
- andrew-repro-test at 20.123.40.15

Are these still required? And if not can they be deleted or given to Robert for now if he requires Administrative access?

**Comment by andrew-m-leonard** [comment] 2024-02-14 10:55
@sxa I'd like to **keep andrew-repro-test at 20.123.40.15** please, as that's a Windows box I am currently using for repro build testing, is there a place I can see where it is assigned to me?

The other two can be removed
thanks Stewart

**Comment by sxa** [comment] 2024-02-14 11:19
> @sxa I'd like to **keep andrew-repro-test at 20.123.40.15** please, as that's a Windows box I am currently using for repro build testing, is there a place I can see where it is assigned to me?
> 
> The other two can be removed thanks Stewart

Sure no problem - you can't see where it's assigned to you unless it's through an issue such as this - otherwise it's only visible in the Azure admin console by how they were named :-)

**Comment by roberttoyonaga** [comment] 2024-02-14 14:14
>Hi @roberttoyonaga - can you clarify why Administrative level access is required for this? In general our tests run as a normal user without special privileges so I would expect that any debugging of failures would not require administrative access.

Hi @sxa this is my first time through this workflow so I am not 100% sure what level of access I'll need to complete this task. I don't know what these machines are already equipped with, but I'll need to build and install the JDK, as well as debugging tools like gdb and a terminal editor. If you don't foresee me needing root access for this then normal user privileges are likely fine for me.

**Comment by sxa** [comment] 2024-02-14 15:49
> > Hi @roberttoyonaga - can you clarify why Administrative level access is required for this? In general our tests run as a normal user without special privileges so I would expect that any debugging of failures would not require administrative access.
> 
> Hi @sxa this is my first time through this workflow so I am not 100% sure what level of access I'll need to complete this task. I don't know what these machines are already equipped with, but I'll need to build and install the JDK, as well as debugging tools like gdb and a terminal editor. If you don't foresee me needing root access for this then normal user privileges are likely fine for me.

Gotcha - thanks. No idea about `gdb` as I've never tried using that on Windows, but in general all of the other things you need can definitely be done as a normal user :-)

Also our windows machines aren't set up with ssh so you'd be getting access to the machine for `rdp`.

**Comment by roberttoyonaga** [comment] 2024-02-14 16:20
> Gotcha - thanks. No idea about gdb as I've never tried using that on Windows, but in general all of the other things you need can definitely be done as a normal user :-)

In that case, that sounds good to me!

**Comment by sxa** [comment] 2024-02-15 12:45
Access granted - will send details through another forum :-)

**Comment by roberttoyonaga** [comment] 2024-02-27 14:52
Hi @sxa I am finished with the windows machine for now. I'd like to return my access. Thank you!

**Comment by sxa** [comment] 2024-03-05 14:03
Thanks - account has now been removed. Closing

**Closed by sxa** 2024-03-05 14:03 UTC
Labels: Temp Infra Access
