### ISSUE TITLE
test-packet-ubuntu1604-x64-1 and test-packet-ubuntu2004-x64-2: Cannot delete workspace

### ISSUE THREAD

**Issue by llxia** [adoptium/infrastructure#2597] opened 2022-06-09 13:28 UTC
- Please put the system name in the title of this issue.
https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1/

- Link to any log file showing the problem:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4965/console

- Please describe the issue:

```
Running on [test-packet-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1/) in /home/jenkins/workspace/Grinder
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
ERROR: Cannot delete workspace :Unable to delete '/home/jenkins/workspace/Grinder/jvmtest/perf/framework-benchmarks/results/20220609083424/benchmark.log'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Exception: hudson.AbortException: Cannot delete workspace: Unable to delete '/home/jenkins/workspace/Grinder/jvmtest/perf/framework-benchmarks/results/20220609083424/benchmark.log'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by llxia** [comment] 2022-06-09 13:30
Same issue on https://ci.adoptopenjdk.net/computer/test-packet-ubuntu2004-x64-2/:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4964/console

**Comment by smlambert** [comment] 2022-06-09 13:42
I have marked -2 offline with a link to this issue, -1 is offline with this message:

```
This agent is offline because Jenkins failed to launch the agent process on it.
```

**Comment by smlambert** [comment] 2022-06-13 14:14
I think this may have occurred as part of @joeyleeeeeee97 testing this [PR](https://github.com/adoptium/aqa-tests/pull/3746) for the addition of a new test (and yes, its container-based).

**Comment by joeyleeeeeee97** [comment] 2022-06-14 02:32
@sxa 
[FrameworkBenchmarks](https://github.com/adoptium/aqa-tests/pull/3746)  is running test with `root` in docker.

**Comment by llxia** [comment] 2022-06-15 14:49
Can we mark https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1/ offline? It is back online now and jobs that land on it will fail. 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5002/

**Comment by sophia-guo** [comment] 2022-07-11 18:33
[build-alibaba-win2012r2-x64-2](https://ci.adoptopenjdk.net/computer/build-alibaba-win2012r2-x64-2/)

two recent builds https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_1/51/
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_1/52/

**Comment by sxa** [comment] 2022-07-12 08:23
> [build-alibaba-win2012r2-x64-2](https://ci.adoptopenjdk.net/computer/build-alibaba-win2012r2-x64-2/)

@sophia-guo Can you put that in a separate issue please(possibly https://github.com/adoptium/infrastructure/issues/2209 if you want to re-use one)  as the cause on Linux vs Windows is unlikely to be the same. Thanks.

**Comment by sxa** [comment] 2022-07-15 10:10
NOTE: These machines are likely to be replaced soon as part of #2666

**Comment by sxa** [comment] 2023-01-12 10:44
Closing as they have been decomissioned

**Closed by sxa** 2023-01-12 10:44 UTC
Labels: arch:x64, provider:packet, systemdown
