### ISSUE TITLE
build-osuosl-aix71-ppc64-2: tests which create core files fail

### ISSUE THREAD

**Issue by lumpfish** [adoptium/infrastructure#1918] opened 2021-02-10 09:50 UTC
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.functional_ppc64_aix/21/consoleFull
Tests which analyse the contents of a core file taken during the test are failing on build-osuosl-aix71-ppc64-2.  The error messages suggest the core file is not actually being written successfully:
```
21:29:10  Testing: Run !allclasses
21:29:10  Test start time: 2021/02/08 13:29:09 Pacific Standard Time
21:29:10  Running command: /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core.dmp
21:29:10  Time spent starting: 29 milliseconds
21:29:11  Time spent executing: 1688 milliseconds
21:29:11  Test result: FAILED
21:29:11   [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
21:29:11   [OUT] Loading image from DTFJ...
21:29:11   [OUT] 
21:29:11   [OUT] Could not load dump file and/or could not load XML file: Image file '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/output_16128142891542/cmdLineTester_classesdbgddrext_1/j9core.dmp' not found.
21:29:11   [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
21:29:11   [OUT] > DDR is not enabled for this core file, '!' commands are disabled
21:29:11   [OUT] > 
```
To rerun one of the failing tests: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=testDDRExt_General_0

**Comment by lumpfish** [comment] 2021-03-10 12:27
Still seeing this on the jdk16 milestone builds: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/136/

**Comment by lumpfish** [comment] 2021-03-15 11:58
This affects more than just `build-osuosl-aix71-ppc64-2` - also seen on `test-osuosl-aix72-ppc64-1` running jdk-16+36_openj9-0.25.0 (https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.functional_ppc64_aix/38)

**Comment by Haroon-Khel** [comment] 2021-03-16 12:08
Just a quick summary: 

These tests also fail on jdk 11 open j9 on all of our aix machines except for test-ibm-aix71-ppc64-2. Despite the error message received in these tests

```
JVMDUMP012E Error in System dump: cannot find core file: "A file or directory in the path name does not exist.". check "ulimit -Hc" is set high enough
```
ulimit -Hc for the jenkins user, on the failing machines, is set to unlimited which is the same as ulimit -Hc on that of the passing machine (test-ibm-aix71-ppc64-2)

**Comment by Haroon-Khel** [comment] 2021-03-16 12:09
@lumpfish Just a heads up, this failing jdk 16 openj9 ddr test passes on test-ibm-aix71-ppc64-2
https://ci.adoptopenjdk.net/job/Grinder/7773/console

**Comment by sxa** [comment] 2021-03-18 11:44
I believe this is happening when the user is added to the `rtclk` role (as per the changes in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1874/files to resolve https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1803 around the start of February) ... It could certainly make some sense that if you need real time operation that core dumps might be prevented as the could impact timings.

**Comment by Haroon-Khel** [comment] 2021-03-18 11:58
@sxa Ill test this hypothesis out on ojdk06 (aix test environment), on which the ddr tests were passing, but if I recall I dont think I ran the `rtclk` role on this machine

**Comment by Haroon-Khel** [comment] 2021-03-18 12:50
The ddr tests on ojdk06 still passed despite running the `rbac` role on the machine. I even rebooted the machine to see if that was required for the changes to take effect. The ddr tests still passed

**Comment by sxa** [comment] 2021-03-18 13:04
How are you running them?

**Comment by Haroon-Khel** [comment] 2021-03-18 13:18
Whenever I run tests on a machine directly, I use this [guide](https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#run-sanity-system-tests-on-jdk10_x86-64_linux_openj9-sdk). In this case changing

```
export BUILD_LIST=functional
...
gmake _<any of the ddr tests>
```

**Comment by Haroon-Khel** [comment] 2021-03-18 13:20
>And can the machine definitely generate core dumps?

The machine passes the ddr tests and reading the logs, I find lines like

```
     [exec] JVMDUMP034I User requested System dump using '/home/jenkins/openjdk-tests/TKG/../TKG/output_16160715273376/testDDRExt_General_0/DDREXT.J9CORE.DMP' through com.ibm.jvm.Dump.SystemDump
     [exec] JVMDUMP010I System dump written to /home/jenkins/openjdk-tests/TKG/../TKG/output_16160715273376/testDDRExt_General_0/DDREXT.J9CORE.DMP
```

While failing machines consistently have error logs containing 

```
12:58:31       [exec] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/output_16160721956057/testDDRExtJunit_MonitorsAndDeadlock4_1/DDREXT.J9CORE.DMP' in response to an event
12:58:31       [exec] JVMDUMP012E Error in System dump: cannot find core file: "A file or directory in the path name does not exist.". check "ulimit -Hc" is set high enough
```

**Comment by sxa** [comment] 2021-03-18 13:36
And was it definitely running as the `jenkins` user which the role modifies?

**Comment by Haroon-Khel** [comment] 2021-03-18 13:45
The tests were definitely running as the jenkins user. 

Im not too familiar with the `rbac` role, but theres nothing in it that specifies modifying config for the jenkins user. Does this role need to run as the jenkins user? If so, it needs 

```
become: yes
become_user: jenkins
```
on each of the tasks in the role

**Comment by sxa** [comment] 2021-03-18 13:48
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/jenkins_user/tasks/main.yml#L66 in the playbook (which has now been deployed over all AIX boxes I believe) makes it take effect for the jenkins user.

**Comment by Haroon-Khel** [comment] 2021-03-18 13:51
In that case, ill re run the jenkins_user role on ojdk06 aswell

**Comment by Haroon-Khel** [comment] 2021-03-18 14:00
It failed after rerunning the jenkins_user role

```
    [exec] JVMDUMP034I User requested System dump using '/home/jenkins/openjdk-tests/TKG/../TKG/output_16160760083487/testDDRExt_General_0/DDREXT.J9CORE.DMP' through com.ibm.jvm.Dump.SystemDump
     [exec] JVMDUMP012E Error in System dump: cannot find core file: "No such file or directory". check "ulimit -Hc" is set high enough
```

**Comment by sxa** [comment] 2021-03-19 17:13
For reference, the following options on a Grinder should verify both the core dump functionality and the ability to run the metronome tests:
```
BUILD_LIST=functional
TARGET=testList TESTLIST=jsr335tests_SE80_6,testDDRExt_General_0,J9vmTest_2
```
Both of the `test-ibm` machines have been updated with the fix as per the PR above.Results as follows (NOTE: Jenkins agent needs to be restarted after applying the change in order for it to take effect - [pre-restart run on test-ibm-2](https://ci.adoptopenjdk.net/job/Grinder/7870/console)):
- test-ibm-1: [Grinder 7871](https://ci.adoptopenjdk.net/job/Grinder/7871/console) (PASSED)
- test-ibm-2: [Grinder 7879](https://ci.adoptopenjdk.net/job/Grinder/7879/console) (FAILED)
- build-osuosl-2: [Grinder 7872](https://ci.adoptopenjdk.net/job/Grinder/7872/console) (FAILED)

**Comment by sxa** [comment] 2021-03-20 10:17
Removing the `rtclk` role from the `jenkins` user generally allows core dumps to be produced successfully although on the AIX7.2 machines it's still having problems, although I think from the log it is successfully creating a core file, just failing to process it properly. Ref:
- https://ci.adoptopenjdk.net/job/Grinder/7911/ (First AIX7.2 system)
- https://ci.adoptopenjdk.net/job/Grinder/7913/ (Second AIX7.2 system)

On this basis I don't think the AIX7.2 machines are showing the same "unable to create a core dump" problem that we've seen on other systems.

**Comment by sxa** [comment] 2021-03-20 11:21
@jdekonin @AdamBrousseau I can't see any AIX 7.2 machines in the OpenJ9 CI. Do you have any on your intranet connected to jenkins that you could fire a quick tests at? OpenJDK8+OpenJ9, functional suite with `testList TESTLIST=jsr335tests_SE80_6,testDDRExt_General_0,J9vmTest_2` as the `TARGET` (the "General" one is the important one but the others are just to verify other things aren't broken ont he same environment so I've been running them all together :-) )

**Comment by AdamBrousseau** [comment] 2021-03-21 06:05
Ran a grinder internally (14349) on 7.2 (on paix822) with the TARGET above. All 3 passed.
Also, on that machine
```
# lsauth ojdk.rtclk
1420-001 Authorization "ojdk.rtclk" does not exist.
```

**Comment by sxa** [comment] 2021-03-21 13:47
Thanks for confirming - at least that confirms that it can pass on a 7.2 system :-) [That role](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1874) is present, but not active for our `jenkins` users any more so that's not likely to be the cause of the failure.

**Comment by AdamBrousseau** [comment] 2021-03-23 13:34
All our 7.2 systems are  `7200-05-01-2038`

**Comment by aixtools** [comment] 2021-04-02 12:53
For the record - here is a file with AIX builddates - and compareable AIX versions - and pay attention to TL levels as newer TL implies new features, e.g., what `capabilities` can affect. And likely not or insufficiently documented (for the general public).
[os_builddates.txt](https://github.com/AdoptOpenJDK/openjdk-infrastructure/files/6249577/os_builddates.txt)

**Comment by sxa** [comment] 2021-05-14 10:43
That `os_buliddates.txt` would be a good candidate for inclusion into the documentation proposed in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2054

**Comment by Haroon-Khel** [comment] 2021-06-21 16:08
Closing since the core file tests pass on all but test-osuosl-aix72-ppc64-1. This is being discussed in https://github.com/adoptium/infrastructure/issues/2125

**Closed** 2021-06-21 16:08 UTC
Labels: os:aix, provider:osuosl, testFail

**Comment by sxa** [comment] 2021-06-21 16:42
@Haroon-Khel I'm not sure this should necessarily be closed yet. That other discussion is about whether to upgrade the other machine. Are we absolutely certain that we cannot enable core dumps on the old level in a suitable way? If we haven't exhausted other possibilities we can consider how to do this, but I'm a little reluctant to stop testing on the level we currently support things on until we are confident it's 100% mandatory.

**Comment by aixtools** [comment] 2021-10-05 18:54
OK - since #2125 was only about whether to update the AIX 7.2 systems to a later TL (where the core dump issue goes away because of some magical change in the kernel) - as this is closed - do we reopen to actually test the RBAC privilege change I found many moons ago - or do you prefer to know that a down-level TL will fail (but we choose to ignore that).
