### ISSUE TITLE
"Vagrant Playbook Checker / Solaris" github check failing for all PRs

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2694] opened 2022-08-10 13:48 UTC
Sample check link: https://github.com/adoptium/infrastructure/runs/7750861669?check_suite_focus=true
```
Bringing machine 'adoptopenjdkSol10' up with 'virtualbox' provider...
==> adoptopenjdkSol10: Box 'solaris10' could not be found. Attempting to find and install...
    adoptopenjdkSol10: Box Provider: virtualbox
    adoptopenjdkSol10: Box Version: >= 0
==> adoptopenjdkSol10: Box file was not detected as metadata. Adding it directly...
==> adoptopenjdkSol10: Adding box 'solaris10' (v0) for provider: virtualbox
    adoptopenjdkSol10: Downloading: solaris10

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/runner/work/infrastructure/infrastructure/ansible/solaris10
```

**Comment by steelhead31** [comment] 2022-08-26 13:35
Messaged George in slack, about adding the Solaris10 vagrant box to whichever runner(s) run the github action.

the github action Vagrant Playbook Checker / Solaris (pull_request) is constantly failing with the following error :-
Bringing machine 'adoptopenjdkSol10' up with 'virtualbox' provider...
==> adoptopenjdkSol10: Box 'solaris10' could not be found. Attempting to find and install...
    adoptopenjdkSol10: Box Provider: virtualbox
    adoptopenjdkSol10: Box Version: >= 0
==> adoptopenjdkSol10: Box file was not detected as metadata. Adding it directly...
==> adoptopenjdkSol10: Adding box 'solaris10' (v0) for provider: virtualbox
    adoptopenjdkSol10: Downloading: solaris10
An error occurred while downloading the remote file. The error message, if any, is reproduced below. Please fix this error and try again.
Couldn't open file /Users/runner/work/infrastructure/infrastructure/ansible/solaris10
I believe this is because whichever machine the action is running on , does not have the solaris10 vagrant box installed. I have a box file which can be installed on whichever runner(s) needed, is it possible for me to have access to the relevant runners, or alternatively for you to install the box file ( which can be found on vagrant-x64-1: {ip: 150.239.60.120} ) in the following path /home/vagrant5/sftest/Solaris10.box.gz. .. once the file has been transferred and unzipped, it can be added to vagrant with the following..
vagrant box add --name="solaris10" ./Solaris10.box (edited)

**Comment by zdtsw** [comment] 2022-09-07 08:22
i think we are using a random macos runner which can be any from the pool  
maybe we can try to add this "download your solaris10 file " in the "Install dependencies" step ?

**Comment by steelhead31** [comment] 2022-09-08 07:53
@zdtsw , I dont have permissions to upload the box file, I'll get that sorted and upload it  ( I have another file which needs to be hosted in the same place to fix issues with VS2013 on windows ). The github action will need to be amended to download the box file, and import it into vagrant, this only needs to be done if it doesnt already exist.. I'll have a look into this once Im properly back.

**Closed** 2022-09-12 12:47 UTC
Labels: reliability
